### ISSUE TITLE
Use With ViewPager and Fragment

### ISSUE THREAD

**Issue by GauvainSeigneur** [aurelhubert/ahbottomnavigation#1]
Such a great work and made so quickly! 

But I'm stuck to call a fragment with on "onTabSelected" method. How to do this like a TabLayout Widget ? 

Thank's !

**Comment by bingningO** [comment]
@GauvainSeigneur 
I can call fragments by the following...

@Override
                public void onTabSelected(int position) {
                    FragmentTransaction transaction = mFragmentManager.beginTransaction();
                    Log.i("checked id", ""+position);
                    Fragment fragment = FragmentFactory.getInstanceByIndex(position+1);
                    transaction.replace(R.id.content, fragment);
                    transaction.commit();
                }

**Comment by aurelhubert** [comment]
@GauvainSeigneur  & @bingningO Thanks! ;)

**Comment by GauvainSeigneur** [comment]
@bingningO Thanks!
