### ISSUE TITLE
Set none active

### ISSUE THREAD

**Issue by oisinlavery** [aurelhubert/ahbottomnavigation#100]
Allow for none of the items to be active/current. The API could be:

`bottomNavigation.setCurrentItem(-1);` or `bottomNavigation.setNoneCurrent();`

**Comment by aurelhubert** [comment]
#85 
```java
bottomNavigation.setCurrentItem(AHBottomNavigation.CURRENT_ITEM_NONE);
```

**Comment by oisinlavery** [comment]
Beautiful, thanks Aurel.

**Comment by Roopamdutta** [comment]
How to programmatically change between two fragments can any one help me out here please?
