### ISSUE TITLE
'getItem(int)' in 'packagename.MyViewPagerAdapter' 

### ISSUE THREAD

**Issue by RiseKyle** [aurelhubert/ahbottomnavigation#103]
'getItem(int)' in 'packagename.MyViewPagerAdapter' clashes with 'getItem(int)' in android.support.v4.FragmentPagerAdapter'.

**Comment by aurelhubert** [comment]
Is it something related to the library?

**Comment by aurelhubert** [comment]
I close the issue for now. Feel free to re-open it with more details.
