### ISSUE TITLE
How to create a sub-fragment?

### ISSUE THREAD

**Issue by gregEstoke** [aurelhubert/ahbottomnavigation#104]
I have 3 Fragments for each bottomNavigation item. When I'm in the first fragment, (hosting a RecyclerView) I need to be able to launch a new (sub)screen and be able to go back to the recyclerView when backButton is pressed. I also need to stay in the AHBottomNavigation ViewPager...

Any idea about how to design/implement this behaviour?

Maybe it is very easy to do, but I can't figure it out... Thanks for the help.

I also posted this question on SO : http://stackoverflow.com/questions/37938463/ahbottomnavigation-how-to-create-a-sub-fragment

**Comment by tylerjroach** [comment]
Also answered on your SO post, but here's the same response.

I'm assuming you are using a non-swipeable view pager for the 3 fragments. Assign the view pager an id of something like @+id/container.

When you want to launch the subscreen, use a fragment transaction and replace @+id/container. Don't forget to also add the new fragment to the backstack.

    getFragmentManager().beginTransaction()
      .replace(R.id.container, Subfragment.newInstance(),Subfragment.class.getName())
      .addToBackStack(Subfragment.class.getName())
      .commit();

The part that is a little unconventional would be having this subfragment, while still showing the bottom navigation. If you really want this functionality, I'm assuming that when you want to remove the subfragment when a different tab is clicked. 

So in this case, when a tab is clicked, check and see if the subfragment exists, if it does, either popBackStack() or remove the subfragment, then switch to the desired fragment.

This is just one method. You could also write a PagerAdapter that replaces a fragment inside the viewpager.

**Comment by aurelhubert** [comment]
The solution of @tylerjroach is a good one.

I have implemented the next behavior in one of my app to manage correctly the transition between fragment/sub-fragment:

- Create an Activity which will contain the ViewPager
- Create an hosting Fragment which will contain a Fragment for each tab. This fragment will manage a stack `Stack<Fragment>` and can add/remove sub-fragments.

When the user clicks on back, it removes a sub fragment. When the user clicks on the tab that is already selected, it displays the top fragments (and remove all sub fragments).

I could add an example in the sample project if necessary.

**Comment by aurelhubert** [comment]
I will close this issue for now. If you need more details, feel free to ask!

**Comment by sivai2i** [comment]
Hi,
Can you give an example on how to create a sub fragment from parent fragment ?

**Comment by abdelwaheb001** [comment]
"I could add an example in the sample project if necessary."
It's possible to share an example ?
