### ISSUE TITLE
Fragment state not updated warning/error

### ISSUE THREAD

**Issue by charlie-barjel** [aurelhubert/ahbottomnavigation#105]
While running my application, I notice the following console message:

`Fragment state for <Fragment> not updated inline; expected state 3 found 2`

I re-ran the sample ahbottomnavigation app, and it seems the same message appears there.
Everything seems to be functioning ok. But I want to know if this is something I should be concerned about and if there is a fix.

What is causing this warning/error?

**Comment by aurelhubert** [comment]
Maybe something related to this issue? https://code.google.com/p/android/issues/detail?id=202037

**Comment by aurelhubert** [comment]
I think the problem comes from Android. Feel free to re-open the issue if you find something related to the library, thank you.
