### ISSUE TITLE
Can't set padding beetwen item

### ISSUE THREAD

**Issue by Hary25** [aurelhubert/ahbottomnavigation#106]
i can't set padding in java between home and setting. Anyone can help me? 

![bottom](https://cloud.githubusercontent.com/assets/20138245/16355392/8cb2781e-3adf-11e6-9341-eb45b3977006.JPG)

**Comment by aurelhubert** [comment]
It's because the library follows the guidelines of Material Design, you shouldn't use a bottom bar to display less than 3 items or more than 5. If you want to do that, I suggest that you fork the library and adapt the code.
