### ISSUE TITLE
Back press shows previous activity highlighted.

### ISSUE THREAD

**Issue by omeadaen** [aurelhubert/ahbottomnavigation#11]
When I click away from an activity using the bottom navigation and then return to the activity by back pressing.. the old activity / bottom icon is highlighted.

adding: setCurrentPosition(4); to the onresume will, for some reason, cause onresume to run in a loop crashing the program.

Also, is there an option to have the bottom navigation displayed without any options highlighted? maybe a setCurrentPosition(null); type of method call would be nice.

**Comment by aurelhubert** [comment]
@omeadaen I'm not sure to understand what you mean by "When I click away from an activity using the bottom navigation". The component should only display fragments: https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-usage

I have tried to execute "bottomNavigation.setCurrentItem(4);" in the "onResume" method but nothing wrong happens for me. Have you more details?

**Comment by aurelhubert** [comment]
@omeadaen Do you have more details about the problem? I will close the issue for now, open it again if you think it's a bug, thanks.
