### ISSUE TITLE
Inflate bottom navigation from XML menu resources

### ISSUE THREAD

**Issue by pengan1987** [aurelhubert/ahbottomnavigation#112]
For multi-flavour project, use flavour specific XML resource is more maintainable, inspired by [roughike's Bottombar](https://github.com/roughike/BottomBar/) I wrote an XML menu resource adapter/inflator for AHBottomNavigation, hope it can helps someone.

https://gist.github.com/pengan1987/5e8cecd9902a799a238e7cd7ffe9fd06

Usage:
```java
AHBottomNavigation ahBottomNavigation = (AHBottomNavigation)findViewById(R.id.bottom_navigation);

AHBottomNavigationAdapter navAdapter = new AHBottomNavigationAdapter(this, R.menu.menu_bottom_nav);

navAdapter.setupWithBottomNavigation(ahBottomNavigation);

//Show badge on navigation item specified by id
ahBottomNavigation.setNotification("3", navAdapter.getPositionByMenuId(R.id.nav_message));
```

**Comment by aurelhubert** [comment]
Added in 1.3.2, thanks!
