### ISSUE TITLE
title

### ISSUE THREAD

**Issue by sarang1996** [aurelhubert/ahbottomnavigation#113]
How to remove title from bottom icon,i just want to show my custom icons. help ! @aurelhubert

**Comment by aurelhubert** [comment]
The title is only displayed when you have 3 items in the bottom bar. If you have more items, the titles will be hidden (except if you use `setForceTitlesDisplay`). If you want a custom behavior, feel free to fork the library.

**Comment by sarang1996** [comment]
i don't understand how to remove titles? you have any method for that? @aurelhubert

**Comment by aurelhubert** [comment]
As I said, you can only manage to display or not the titles when you have 4 or 5 items. If you have 3 items, it's currently not possible (but you can fork the library and add the functionality).

**Comment by sarang1996** [comment]
yeh i understood, but when i remove the title from bottom the white space is there because of may be transaction effect over there, so how i can remove white space, i don't know how to do that exactly so. @aurelhubert

**Comment by aurelhubert** [comment]
If you want to remove the title when you have 3 items in the bottom navigation, I suggest you to rewrite the navigation item layout (remove the title and center the icon) here: https://github.com/aurelhubert/ahbottomnavigation/blob/master/ahbottomnavigation/src/main/res/layout/bottom_navigation_item.xml and update `AHBottomNavigation.java`.

**Comment by sarang1996** [comment]
i have 5 items in the bottombar. @aurelhubert

**Comment by aurelhubert** [comment]
So update this one: https://github.com/aurelhubert/ahbottomnavigation/blob/master/ahbottomnavigation/src/main/res/layout/bottom_navigation_small_item.xml
