### ISSUE TITLE
Cross-Fade animation switching views?

### ISSUE THREAD

**Issue by amanzan** [aurelhubert/ahbottomnavigation#114]
Would it be possible to add a cross-fade animation when switching views, like it is stated in Material guidelines?

![bottomnav](https://cloud.githubusercontent.com/assets/3911627/16593856/6b648606-42b5-11e6-9dfe-ced668150c07.gif)

**Comment by aurelhubert** [comment]
You can check the last version of the demo. The animation are done inside the fragment which will be displayed (in the method `willBeDisplayed()`). You can customize the animation for your needs.
