### ISSUE TITLE
Change ripple background?

### ISSUE THREAD

**Issue by teddywilson** [aurelhubert/ahbottomnavigation#116]
Is there any way to change the ripple background for the individual items. Running my app in lower SDKs on the emulator displays strange backgrounds for the items when clicked/hovered.

**Comment by aurelhubert** [comment]
In the next version (1.4.0), there will be a new method `setSelectedBackgroundVisible(boolean visible)` to show a custom background when the tab is touched/selected (you can override the color in you colors.xml: `colorBottomNavigationSelectedBackground`).
