### ISSUE TITLE
lag transition when using fragment

### ISSUE THREAD

**Issue by yfsx** [aurelhubert/ahbottomnavigation#118]
hi, thanks for sharing this amazing lib!

i just implemented this lib with 5 fragments, but it seems there's a slight delay when i switch between different fragments.

is there any help or tricks for this problem?
thanks

**Comment by aurelhubert** [comment]
Hi @yfsx, have you tried the demo project? Do you have the same problem?

**Comment by aurelhubert** [comment]
I close the issue for now. Feel free to re-open it with more details.
