### ISSUE TITLE
How can I make Notification circle smaller ?

### ISSUE THREAD

**Issue by whyalwaysmea** [aurelhubert/ahbottomnavigation#120]
I use `setNotification(" ", 0)`, but the circle is so big and ugly, it can be a little dot, that will be better!
How can I make it smaller? I attempt to use `setNotificationBackground(drawable)`
`<shape xmlns:android="http://schemas.android.com/apk/res/android">

    <solid android:color="#f00" />
    <size android:height="2dp" android:width="2dp" />
    <corners android:radius="2dp" />
</shape>`
but it only change the radius, not change the size.

**Comment by aurelhubert** [comment]
You can override `bottom_navigation_notification_width` & `bottom_navigation_notification_height` in your dimens.xml (for example 8dp).

**Comment by geekqian** [comment]
![image](https://user-images.githubusercontent.com/15983385/34639642-f5b448c6-f31e-11e7-9cae-ffcfd9333967.png)
![image](https://user-images.githubusercontent.com/15983385/34639664-447233f6-f31f-11e7-950a-b45dbf075f64.png)
