### ISSUE TITLE
How i can to delete the animation of the navigation

### ISSUE THREAD

**Issue by manudelf** [aurelhubert/ahbottomnavigation#121]
hello, i need to delete the animations of the bottonnavigator, when i click on one of the botton , i need to delete the movement of the botton up.

**Comment by aurelhubert** [comment]
Hi, the animations are parts of the [Material Design guidelines](https://material.google.com/components/bottom-navigation.html#bottom-navigation-behavior). For now, it's not possible to disable them, but you can fork the project and add this feature.

**Comment by krupal1010** [comment]
How can i fork??
