### ISSUE TITLE
Bottom navigation not showing original color Icon

### ISSUE THREAD

**Issue by AwesomePeople** [aurelhubert/ahbottomnavigation#122]
Hi everybody,
I am facing with the issue that icon in  bottom navigation not showing true original color
Example facebook icon <url>http://image.flaticon.com/icons/svg/145/145802.svg</url> , after i add as AHBottomNavigationItem, that became just only accent color or grey color

**Comment by aurelhubert** [comment]
Hi, that's the expected behavior: https://material.google.com/components/bottom-navigation.html#bottom-navigation-style

> **Color**
>
>Tint the current bottom navigation action (including the icon and any text label present) with the app’s primary color.

If you want to change that, you can fork the library and implement your own behavior.
