### ISSUE TITLE
Scroll bug

### ISSUE THREAD

**Issue by cowfighting** [aurelhubert/ahbottomnavigation#125]
hi, thanks for this great library.
When i have three tabs, each tab can scroll independently.  But only one tab can scroll, the others stay stationary and cannot scroll.

**Comment by aurelhubert** [comment]
Hi, sorry but I don't understand what is the problem. Can you give me more details (screenshots, codes, your implementation, etc.)? Thanks.

**Comment by cowfighting** [comment]
Sorry, it's my problem.
thanks.

**Comment by aurelhubert** [comment]
Alright, if you find a problem, open a new issue :) Thanks.
