### ISSUE TITLE
Item background selection color

### ISSUE THREAD

**Issue by Drakot** [aurelhubert/ahbottomnavigation#127]
Hello,

Is it possible to set the selected item color? I need the item to stay selected until another item is clicked. It works with the icon color but not the background.

**Comment by aurelhubert** [comment]
> Is it possible to set the selected item color?

Yes: `bottomNavigation.setAccentColor(Color.parseColor("#F63D2B"));`

>  I need the item to stay selected until another item is clicked.

That's the current behavior.

> It works with the icon color but not the background.

Not sure to understand what is the problem.

**Comment by Drakot** [comment]
![captura de pantalla 2016-07-28 a las 10 31 37](https://cloud.githubusercontent.com/assets/10567874/17206216/ec605432-54ae-11e6-883d-54bb409256e3.png)
This the normal behaviour. As you can see it is using the accent color in the image(white in this case). That is correct, but the background of the item is transparent

![captura de pantalla 2016-07-28 a las 10](https://cloud.githubusercontent.com/assets/10567874/17206256/2336e71e-54af-11e6-9b69-e3ac90e50089.png)

This is the background of the item when touched, but when the finger is lifted it goes back to transparent, Isn't it possible to make it stay selected so that the item background is grey instead of transparent? And more important, can I set that color to replace that grey?


Thank you!

**Comment by aurelhubert** [comment]
The gray effect is displayed on Android pre-Lollipop (since Lollipop, the system displays a ripple effect when you touch a tab). If you want to change that, you can fork the library and set a specific background for the layout tab (with for example, a color for the selected state).

**Comment by Ayesha-Fazal** [comment]
is it possible to change the color of selected item
