### ISSUE TITLE
navigation button disappear after change fragment

### ISSUE THREAD

**Issue by MansoorJafari** [aurelhubert/ahbottomnavigation#129]
Whenever in a fragment the scroll is being used, the navigation button disappears and at this point if the back button is being tapped and the fragment moves, it does not appear any more.

Please Help.

**Comment by developer1011** [comment]
@MansoorJafari thanks for posting this. I am facing very same issue. I have a fragment pager adapter. In one of the fragment I scroll and the navigation buttons disappear. Now if I switch to another tab programmatically using setCurrentItem(int index), the bottom navigation is fully gone, there is no way for user to interact with it.

If you come to know about a solution please let me know. Thanks.

**Comment by aurelhubert** [comment]
Hi @MansoorJafari, does the answer of @developer1011 fixed your problem? I will close this issue for now but feel free to re-open it with more details if necessary, thanks.
