### ISSUE TITLE
Hiding the Bottom Navigation when keyboard opens?

### ISSUE THREAD

**Issue by TheMaxCoder** [aurelhubert/ahbottomnavigation#130]
Hi Lib is amazing, I really appreciate your effort and I wanted to know Is there anyway to hide the bottom navigation bar when keyboard pops on screen?
am using a fragment where user has to fill up a form with multiple `EditTexts` and each time keyboard opens it put Bottom bar on top of the keyboard.

if there were only one `EditText` i could have used `FocusChangeListerner` but I have multiple and  I was wondering how can I come over this issue?

Thanks

**Comment by aurelhubert** [comment]
@TheMaxCoder It can be tough to manage the keyboard in Android (specially to detect when it opens or closes). I suggest you to try to open the keyboard above the bottom bar by adding this to your Activity (in your Manifest.xml): 
```xml
android:windowSoftInputMode="adjustPan|stateHidden"
```
Feel free to re-open the issue if you still have a problem.

**Comment by shagspb** [comment]
I have the same problem. Your method did not work :(

**Comment by firebaseempower** [comment]
did'nt work with numeric keyboard :(
