### ISSUE TITLE
Notification Icons

### ISSUE THREAD

**Issue by MarcoMauricio** [aurelhubert/ahbottomnavigation#134]
I see that you have a value set for the notification width(bottom_navigation_notification_width) but  looking at the layout files, this value is never used. Is this intended because of size issues ? 

Setting this value in the xml would be a quick fix for those of us that are trying to use icons instead of text. We could just set the setNotificationBackground(Drawable).

**Comment by aurelhubert** [comment]
Actually, the value `bottom_navigation_notification_width` & `bottom_navigation_notification_height` are used in bottom_navigation_item.xml & bottom_navigation_small_item.xml. You can override the value in your project to change the size of the notification.
