### ISSUE TITLE
Actionbar is not showing up

### ISSUE THREAD

**Issue by Anilchahal** [aurelhubert/ahbottomnavigation#135]
For below lollipop devices, action bar is not showing while scrolling up and down. When I reach the top of my recyclerview only then Action bar is visible. Ideally, both buttons(bottom nav and Action bar) should be in sync. Bottom nav button working fine on all devices.  Please note this is happening only for below lollipop.  Can I expect a quick solution for this bug?

**Comment by aurelhubert** [comment]
@Anilchahal Not sure to understand what is the problem. Have you tried the demo project on your device?

**Comment by aurelhubert** [comment]
I close the issue for now. Feel free to re-open it with more details.
