### ISSUE TITLE
Title text maxlines

### ISSUE THREAD

**Issue by jemshit** [aurelhubert/ahbottomnavigation#137]
Hi, i have navigation with 4 items, 1 item has title longer. That title is shown in normal unselected state, but if i select it, half of title becomes invisible. How can i change title maxHeight to 2 so it can display my whole long title

**Comment by aurelhubert** [comment]
The title should only be on one line (https://material.google.com/components/bottom-navigation.html#bottom-navigation-style). If your title is too long, try to change it or fork the library to display it correctly.
