### ISSUE TITLE
Icon resizing

### ISSUE THREAD

**Issue by phehaz** [aurelhubert/ahbottomnavigation#138]
Question.
I can't seem to find anything for changing the size of the ImageViews, i'd like to change the size of the icons to be a bit larger - is this possible with the current state of the library?

**Comment by aurelhubert** [comment]
@phehaz It's not possible with the current state of the library (because if follows the Material Design guidelines https://material.google.com/components/bottom-navigation.html#bottom-navigation-specs).

Feel free to fork the library.

**Comment by GitHubMurt** [comment]
For my clients Material Design doesn't matter.
It would be nice if you include resizing option.

**Comment by Gaetano-Dati** [comment]
Please include resizing options for icons!

**Comment by File5** [comment]
You don't need to fork the library to change the size of icons.
You can peek at the "res" folder of the library and override dimens in your project.

For example I want my icons to be 30dp.
So my project's dimens.xml looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <dimen name="bottom_navigation_icon">30dp</dimen>
    <dimen name="bottom_navigation_small_margin_top">12dp</dimen>
    <dimen name="bottom_navigation_small_margin_bottom">10dp</dimen>
</resources>
```

**Comment by Coehill** [comment]
@File5 How do you access AHBottomNavigationView's res folder from within your own project?

**Comment by File5** [comment]
@Coehill I've just tried to put file in **my project's** res folder and that works. The key is to have the same dimen names as in the original library.
