### ISSUE TITLE
Firebase failure due to this git import

### ISSUE THREAD

**Issue by jxc02** [aurelhubert/ahbottomnavigation#139]
Firebase API initialization failure
When I remove     compile 'com.aurelhubert:ahbottomnavigation:1.3.3'     everything is fine

**Comment by aurelhubert** [comment]
@jxc02 Do you still have the problem? Can you give me more details?

**Comment by jxc02** [comment]
All I remember happening is Firebase just didn't work when I imported. and it went back to normal when I removed 'com.aurelhubert:ahbottomnavigation:1.3.3'
Sorry I can't be of more help..

**Comment by aurelhubert** [comment]
I have tried with:

```xml
    compile 'com.google.firebase:firebase-auth:9.6.1'
    compile 'com.google.firebase:firebase-database:9.6.1'
    compile 'com.aurelhubert:ahbottomnavigation:1.5.1'
```

And everything seems okay.
