### ISSUE TITLE
Auto show/hide enable and disable programatically

### ISSUE THREAD

**Issue by rpandey91** [aurelhubert/ahbottomnavigation#142]
How to change show/hide property dynamically, please help

**Comment by zokipirlo** [comment]
it's a little late, but maybe will help someone else.
Check methods `setBehaviorTranslationEnabled` and `restoreBottomNavigation`.

**Comment by aurelhubert** [comment]
Not sure to understand what you need exactly, but you can use `hideBottomNavigation()` and `restoreBottomNavigation()` to show/hide the Bottom Navigation.

**Comment by accurate** [comment]
I know this is closed, but I'm looking to disabled the auto-hide when scrolling. I know there's restoreBottomNavigation() but I want to disable the auto-hide completely (if possible).

Thanks!

**Comment by hungvu193** [comment]
try  bottomNavigation.setBehaviorTranslationEnabled(isHide);
