### ISSUE TITLE
Unable to style the bottom navigation bar

### ISSUE THREAD

**Issue by spongyboss** [aurelhubert/ahbottomnavigation#143]
I have tried everything to change the background colour, accent colour, inactive colour for the bottom nav bar to no success. It always comes out with a grey background and white icons. I do not know what to do anymore:

XML 
`<com.aurelhubert.ahbottomnavigation.AHBottomNavigation
    android:id="@+id/bottom_navigation"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom"/>`

Java

`AHBottomNavigation bottomNavigation = (AHBottomNavigation)findViewById(R.id.bottom_navigation);

        AHBottomNavigationItem homeItem = new AHBottomNavigationItem("Home",R.drawable.ic_home2);
        AHBottomNavigationItem reportItem = new AHBottomNavigationItem("Report Card",R.drawable.ic_report2);
        AHBottomNavigationItem accountItem = new AHBottomNavigationItem("Account",R.drawable.ic_user2);

        bottomNavigation.addItem(homeItem);
        bottomNavigation.addItem(reportItem);
        bottomNavigation.addItem(accountItem);

      bottomNavigation.setDefaultBackgroundColor(Color.parseColor("#04294B"));

      bottomNavigation.setAccentColor(Color.parseColor("#F63D2B"));
      bottomNavigation.setInactiveColor(Color.parseColor("#747474"));`

**Comment by 0wzZZzz6** [comment]
I've encounter this also. please fix. thanks

**Comment by bsobe** [comment]
@spongyboss Use any **color parameter** constructor
new AHBottomNavigationItem(@StringRes int titleRes, @DrawableRes int drawableRes, **@ColorRes int colorRes**)

**Comment by abumoallim** [comment]
Facing the same issue , any solution ?

**Comment by lecho** [comment]
@spongyboss, @0wzZZzz6, @abumoallim  
solution described in issue #56 works form me. I had to use `bottomNavigation.setColored(false);`. 
So my configuration now looks like this:
```java
        bottomNavigation.setColored(false);//!!!
        bottomNavigation.setDefaultBackgroundColor(backgroundColor);
        bottomNavigation.setAccentColor(accentColor);
        bottomNavigation.setBehaviorTranslationEnabled(false);//no coordinator layout
        bottomNavigation.setOnTabSelectedListener(new BottomNavigationItemListener());
```

**Comment by aurelhubert** [comment]
@spongyboss, @0wzZZzz6, @abumoallim does the solution of @lecho works for you?

If not, give me more details about your implementation, thanks.

**Comment by aurelhubert** [comment]
I'll close this issue for now. Feel free to re-open it if we have more details about the problem.
