### ISSUE TITLE
No border in Pre lollipop devices

### ISSUE THREAD

**Issue by vdtn359** [aurelhubert/ahbottomnavigation#144]
The bottom bar shows no border in older devices. I tried many solutions like adding a background xml as well as adding a view to the top of AHBottomNavigation dynamically but they didn't work. Is there any solution for this?

**Comment by jesuisnicolasdavid** [comment]
i am looking to draw a line on the top border of the bottom bar but i am still struggling to implement it. I tried a background xml and a view inside AHBottomNavigation but nothing is working...

**Comment by aurelhubert** [comment]
Added a method `setDefaultBackgroundResource(@DrawableRes int defaultBackgroundResource)`.

**Comment by aurelhubert** [comment]
Added in 1.4.0
