### ISSUE TITLE
What is the difference between AHBottomNavigation.OnTabSelectedListener and AHBottomNavigation.OnNavigationPositionListener ?

### ISSUE THREAD

**Issue by lv910929** [aurelhubert/ahbottomnavigation#146]
@aurelhubert

**Comment by aurelhubert** [comment]
`OnTabSelectedListener.onTabSelected(int position, boolean wasSelected)`
>Called when a tab is clicked (with the position of the tab, and if it was already selected).

`OnNavigationPositionListener.onPositionChange(int y)``
>Called during the animation of the Bottom Navigation.
