### ISSUE TITLE
Tab icons disposition in landscape

### ISSUE THREAD

**Issue by igoriols** [aurelhubert/ahbottomnavigation#149]
Hello @aurelhubert , thanks for this great lib! Is it possible to make tab icons fill phone width in landscape mode?

Thanks in advance!

**Comment by aurelhubert** [comment]
The current implementation follows the Material Design guidelines : https://material.google.com/components/bottom-navigation.html#bottom-navigation-specs

>Width minimum and maximum (these values include padding):
>Maximum: 168dp
>Minimum: 80dp

But feel free to fork the project.
