### ISSUE TITLE
Displaying less than MIN items with Classic Mode.

### ISSUE THREAD

**Issue by AndreySoloviov** [aurelhubert/ahbottomnavigation#151]
```
		if (items.size() == MIN_ITEMS || forceTitlesDisplay) {
			createClassicItems(linearLayout);
		} else {
			createSmallItems(linearLayout);
		}
```
Can you please change == to <= here: "items.size() == MIN_ITEMS"

i know that it's 'bad practice' to have less than MIN_ITEMS. 
but my app logic for some very little group of users disables some of tabs. so there can be 2 items.
and i think displaying here Classic Mode is good choice
I've create PR #152

**Comment by zayo** [comment]
A have facing same situation, but rather show 3 items and one is not selectable + Show snackbar to inform what happend when clicked than go against design at all.
Just an idea :)

**Comment by aurelhubert** [comment]
Added in 1.4.0
