### ISSUE TITLE
How to find Navigation Bottom is Hide? ( Question )

### ISSUE THREAD

**Issue by IRMobydick** [aurelhubert/ahbottomnavigation#153]
Hi there, First of all thanks for library
Second, The question is: How can find navigation bottom is hide or not?
I'm using `hideBottomNavigation()` to hide the view, Now i need to know the visibility of view to use `restoreBottomNavigation()` to restore it.

Thanks :)

**Comment by aurelhubert** [comment]
Added in 1.4.0: `isHidden()`

**Comment by samosudov** [comment]
Required:
`AHBottomNavigation.setBehaviorTranslationEnabled(true);`
