### ISSUE TITLE
Select animation sticks on first item

### ISSUE THREAD

**Issue by ChristopherWalz** [aurelhubert/ahbottomnavigation#158]
![stick](https://cloud.githubusercontent.com/assets/962334/18864682/b905efd4-8497-11e6-864f-4ce251051689.jpeg)
The grey circle always sticks in the background after selecting the first item. This only happens for the first item! When selecting the second or third item, the animation fades out correctly.

Is this an issue or did I failed to configure this correctly?

Android 6.0.1
OxygenOS 3.2.6

**Comment by Scraft** [comment]
I had this same issue, however, I changed my code from:

`setBehaviorTranslationEnabled(true);`

to

`setBehaviorTranslationEnabled(true);`

And the issue is no longer occuring - obviously this isn't a proper fix, just sharing in case it helps.

**Comment by ChristopherWalz** [comment]
Same for me. I tried `true` and `false` (`false` should be the default anyway).

**Comment by KirillMakarov** [comment]
@Scraft 
Can you share some code with your workaround?

**Comment by Scraft** [comment]
Sorry for the confusion; I have concluded that sometimes the first tab sticks, and sometimes it doesn't, I can't narrow down exactly what causes it. After I made the above suggested code change it worked the next couple of times I run the project, but now I notice it often still sticks.

So please include myself in the list of people who are keen to see a proper fix to this issue.

**Comment by aurelhubert** [comment]
The PR #132 has created a bug, I have added a directory layout-v21 to fix it. The version 1.5.1 is available.

**Comment by samkazmi** [comment]
The is is not fixed yet. @aurelhubert

**Comment by parthilystnow** [comment]
Facing same issue in Android 6.0.1

**Comment by samkazmi** [comment]
``` 
bottom_navigation.setOnTabSelectedListener { position, _ ->
            // Do something cool here...
            if (position == 0) {
                bottom_navigation.refresh()
            }
}
```

I did this
