### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by PaulWoitaschek** [aurelhubert/ahbottomnavigation#161]
It would be very helpful if you could use git tags and github versioning. 

Right now its very difficult to find out what was in which release (besides reading the changelog)

**Comment by aurelhubert** [comment]
Thanks for the suggestion, I will try to use it for the next releases. Do you have any advices?

**Comment by PaulWoitaschek** [comment]
Well a minimal release looks like this:

1. You bump your version up
2. You add a tag locally `git tag v1.2.3`
3. You push the tag `git push origin --tags`

Btw, I see that you just made your first release, congrats :)
