### ISSUE TITLE
How to unset selectable value

### ISSUE THREAD

**Issue by groupedsi** [aurelhubert/ahbottomnavigation#162]
Hello, I use the bottom navigation, and plugin it's awesome. But when my activity load the first item it's selected but i don't want, it's possible to have no selected item? And it's possible to removed selected item when i click in the navigation menu, because i have item in the principal menu and not in the bottom navigation bar. Thx

**Comment by aurelhubert** [comment]
I let you check this issue: #85

**Comment by groupedsi** [comment]
thx! :)
