### ISSUE TITLE
Unselect all?

### ISSUE THREAD

**Issue by st-f** [aurelhubert/ahbottomnavigation#164]
This library is the second one I try and both suffer from the same problem. You nearly never have an app where all the navigation goes at the bottom. There's always a case where you need to unselect all. Would it be possible to add that?

**Comment by aurelhubert** [comment]
I let you check this issue: #85 (referenced in #100 & #162).

**Comment by st-f** [comment]
Thanks for your quick answer, but unfortunately this causes the whole bar the go white : http://imgur.com/a/TwBXU

**Comment by aurelhubert** [comment]
@st-f I have added this line in the Demo project and everything works fine:

```java
bottomNavigation.setCurrentItem(AHBottomNavigation.CURRENT_ITEM_NONE);
```

I suggest you to check everything is okay on your side, and give me more details if you think the problem comes from the lib, thanks.

**Comment by zahid--ali** [comment]
@st-f and @aurelhubert  did you guys found the solution to http://imgur.com/a/TwBXU this issue? I want to keep the default color on unselect all @color/primaryColor

**Comment by aurelhubert** [comment]
You can set the default color with `setInactiveColor(int color)`, and unselect all items with `bottomNavigation.setCurrentItem(AHBottomNavigation.CURRENT_ITEM_NONE);`. Do you have any problems with that?

**Comment by zahid--ali** [comment]
I was using AHBottomNavigationAdapter to change color on select and on unselect all the color of the BottomNavigation was changing to white, while I was using white icons according to the design. It was affecting as seen in http://imgur.com/a/TwBXU. Now where ever I am using this line
bottomNavigation.setCurrentItem(AHBottomNavigation.CURRENT_ITEM_NONE)
I am using 
bottomNavigation.setDefaultBackgroundColor(prams)

**Comment by aurelhubert** [comment]
Hum, personally, I think you shouldn't change the color in the adapter (if you want to follow the guidelines of Material Design). I understand now what you want to do, and I suggest you to fork the library if you want to add a new method. I think one color for the unselected items and one for the selected item is enough, and easier to understand for your users, but it's your responsibility to select which design you want :)
