### ISSUE TITLE
FAB translates up too much when snackbar is shown

### ISSUE THREAD

**Issue by agramian** [aurelhubert/ahbottomnavigation#169]
I noticed this issue in my own project and then ran your demo to confirm that it behaves the same.
It looks like the 72dp bottom margin is being added to the translation amount.
I'm testing on a Moto X 2nd gen running 5.1

See the screenshot below:
![screenshot_2016-10-17-00-59-23](https://cloud.githubusercontent.com/assets/7113257/19429588/4d62bf6e-9405-11e6-9992-5f54719d6567.png)

**Comment by sosite** [comment]
Yeap, I notice the same thing (fortunately I doesn't have FAB in my project yet).

**Comment by JelleBlaauw** [comment]
I have this issue as well. Running on a Nexus 5 with Android 6.0.1.

**Comment by aurelhubert** [comment]
I've made some tests, it seems that the problem appears with the new version of the design library (`24.2.1`), everything works great with the `24.0.0`. When I change the bottom margin of the Snackbar to appear on top of the bottom bar, the FAB move too, I don't understand why...

**Comment by JelleBlaauw** [comment]
Well, it appears that Google has now included [their implementation of BottomNavigation ](https://developer.android.com/reference/android/support/design/widget/BottomNavigationView.html) in the [newest support library](https://developer.android.com/topic/libraries/support-library/revisions.html).

**Comment by agramian** [comment]
Yes but Google's implementation is not tried and true yet and is missing
several customizations that existing 3rd party bottom navigation libraries
already provide like notification badges, ability to customize
text/color/item/animation a bit more etc. So there is still value in
figuring this problem out.

**Comment by JelleBlaauw** [comment]
Alright, that's good to hear. Well, if the issue lies within 24.2.1 maybe it's a good idea to check out the compatibility with 25.0.0. Perhaps this solves things.

**Comment by aurelhubert** [comment]
I have added a new method to manage the behavior of the FloatingActionButton in the version 2.0.0:
```java
bottomNavigation.manageFloatingActionButtonBehavior(floatingActionButton);
```
It should be better, feel free to tell me if it's okay for you.

**Comment by aurelhubert** [comment]
I close this issue for now, feel free to reopen it if you need.
