### ISSUE TITLE
Slow animation changes

### ISSUE THREAD

**Issue by juanlabrador** [aurelhubert/ahbottomnavigation#17]
I am using 4 fragments, all works, but when I pressed a tab, the animation is very slow, not talk about fragment transition, it's about navigation icon focus. Any idea of why? Thanks.

**Comment by aurelhubert** [comment]
@juanlabrador Maybe you're doing too much work in the main (UI) thread? It's a bit difficult to judge without any code :)

**Comment by juanlabrador** [comment]
I understand. Thank you! I implement Asynctask class for init UI and search in SQLite, and solved.
