### ISSUE TITLE
Hiding the Bottom Navigation when keyboard opens

### ISSUE THREAD

**Issue by shagspb** [aurelhubert/ahbottomnavigation#171]
Hello.
I have the same problem:
"Hi Lib is amazing, I really appreciate your effort and I wanted to know Is there anyway to hide the bottom navigation bar when keyboard pops on screen?
am using a fragment where user has to fill up a form with multiple EditTexts and each time keyboard opens it put Bottom bar on top of the keyboard."

Your method did not work:
@TheMaxCoder It can be tough to manage the keyboard in Android (specially to detect when it opens or closes). I suggest you to try to open the keyboard above the bottom bar by adding this to your Activity (in your Manifest.xml):

android:windowSoftInputMode="adjustPan|stateHidden"
Thx.

**Comment by sosite** [comment]
You must watch out with this `SoftInputMode` - many people (like me ;) ) prefer use `adjustResize` mode.
I have working and probably bulletproof code that hides bottom nav if necessary. I can share it if someone will need this.

**Comment by iRYO400** [comment]
@sosite it would be cool!

**Comment by sosite** [comment]
It'll be faster but yesterday ddos for DNSs ruins my plans... The main part I found on stackoverflow but I just connect it with bottom nav.

```java
@Override
protected void onResume() {
    super.onResume();
    getContentView().getViewTreeObserver()
            .addOnGlobalLayoutListener(mLayoutKeyboardVisibilityListener);
}

@Override
protected void onPause() {
    super.onPause();
    getContentView().getViewTreeObserver()
            .removeOnGlobalLayoutListener(mLayoutKeyboardVisibilityListener);
}

private final ViewTreeObserver.OnGlobalLayoutListener mLayoutKeyboardVisibilityListener =
        () -> {
            final Rect rectangle = new Rect();
            final View contentView = getContentView();
            contentView.getWindowVisibleDisplayFrame(rectangle);
            int screenHeight = contentView.getRootView().getHeight();

            // r.bottom is the position above soft keypad or device button.
            // If keypad is shown, the rectangle.bottom is smaller than that before.
            int keypadHeight = screenHeight - rectangle.bottom;
            // 0.15 ratio is perhaps enough to determine keypad height.
            boolean isKeyboardNowVisible = keypadHeight > screenHeight * 0.15;

            if (mKeyboardVisible != isKeyboardNowVisible) {
                if (isKeyboardNowVisible) {
                    onKeyboardShown();
                } else {
                    onKeyboardHidden();
                }
            }

            mKeyboardVisible = isKeyboardNowVisible;
        };

private void onKeyboardShown() {
    mBottomNav.hideBottomNavigation(false);
}

private void onKeyboardHidden() {
    mBottomNav.restoreBottomNavigation(false);
}
```

**Comment by MossoIsai** [comment]
I do not understand the variable getContentView, you could explain it to me, please.
Greeting!

**Comment by MossoIsai** [comment]
public class Principal extends AppCompatActivity {
    private FrameLayout frameLayoutFragment;
    private BottomNavigationView bottomNavigationView;
    private AHBottomNavigation  ahBottomNavigation;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        Log.d("CONSOLE","PAPA onCreate");
        super.onCreate(savedInstanceState);
        setContentView(R.layout.principal);

        frameLayoutFragment = (FrameLayout) findViewById(R.id.myFragemnt);
        ahBottomNavigation = (AHBottomNavigation)findViewById(R.id.bottom_navigation);

        FragmentManager fm = getSupportFragmentManager();
        FragmentTransaction fragmentTransaction = fm.beginTransaction();

        MainActivity mainActivity = new MainActivity();
        fragmentTransaction.replace(R.id.myFragemnt, mainActivity);
        fragmentTransaction.commit();




        AHBottomNavigationItem item1 = new AHBottomNavigationItem("Menú", R.drawable.menu);
        AHBottomNavigationItem item2 = new AHBottomNavigationItem("Favoritos", R.drawable.favoritos_item);
        AHBottomNavigationItem item3 = new AHBottomNavigationItem("Tu orden", R.drawable.item_charola);
        AHBottomNavigationItem item4 = new AHBottomNavigationItem("Perfil", R.drawable.item_perfil);

        ahBottomNavigation.addItem(item1);
        ahBottomNavigation.addItem(item2);
        ahBottomNavigation.addItem(item3);
        ahBottomNavigation.addItem(item4);

        ahBottomNavigation.setTitleState(AHBottomNavigation.TitleState.ALWAYS_SHOW);
        ahBottomNavigation.setTitleState(AHBottomNavigation.TitleState.ALWAYS_SHOW);
        ahBottomNavigation.setTitleState(AHBottomNavigation.TitleState.ALWAYS_SHOW);
        ahBottomNavigation.setTitleState(AHBottomNavigation.TitleState.ALWAYS_SHOW);

        ahBottomNavigation.setOnTabSelectedListener(new AHBottomNavigation.OnTabSelectedListener() {
            @Override
            public boolean onTabSelected(int position, boolean wasSelected) {
                switch (position) {
                    case 0:

                        FragmentManager fm = getSupportFragmentManager();
                        FragmentTransaction fragmentTransaction = fm.beginTransaction();

                        MainActivity mainActivity = new MainActivity();
                        fragmentTransaction.replace(R.id.myFragemnt, mainActivity);
                        fragmentTransaction.commit();

                        return true;
                    case 1:
                        FragmentManager fm2 = getSupportFragmentManager();
                        FragmentTransaction fragmentTransaction2 = fm2.beginTransaction();

                        FragmentFavoritos fragmentFavoritos = new FragmentFavoritos();
                        fragmentTransaction2.replace(R.id.myFragemnt, fragmentFavoritos);
                        fragmentTransaction2.commit();
                        return true;

                    case 2:

                        FragmentManager fm3 = getSupportFragmentManager();
                        FragmentTransaction fragmentTransaction3 = fm3.beginTransaction();

                        FragmentOrden fragmentOrden = new FragmentOrden();
                        fragmentTransaction3.replace(R.id.myFragemnt, fragmentOrden);
                        fragmentTransaction3.commit();
                        return true;


                    case 3:
                        FragmentManager fm4 = getSupportFragmentManager();
                        FragmentTransaction fragmentTransaction4 = fm4.beginTransaction();

                        FragmentPerfil fragmentPerfil = new FragmentPerfil();
                        fragmentTransaction4.replace(R.id.myFragemnt, fragmentPerfil);
                        fragmentTransaction4.commit();
                        return true;

                }
                return  true;
            }
        });
        }


        /*bottomNavigationView = (BottomNavigationView) findViewById(R.id.bottomNavigation);


        FragmentManager fm = getSupportFragmentManager();
        FragmentTransaction fragmentTransaction = fm.beginTransaction();

        MainActivity mainActivity = new MainActivity();
        fragmentTransaction.replace(R.id.myFragemnt, mainActivity);
        fragmentTransaction.commit();


        bottomNavigationView.setOnNavigationItemSelectedListener(new BottomNavigationView.OnNavigationItemSelectedListener() {

            @Override
            public boolean onNavigationItemSelected(MenuItem item) {
                switch (item.getItemId()) {
                    case R.id.item_menu:

                        FragmentManager fm = getSupportFragmentManager();
                        FragmentTransaction fragmentTransaction = fm.beginTransaction();

                        MainActivity mainActivity = new MainActivity();
                        fragmentTransaction.replace(R.id.myFragemnt, mainActivity);
                        fragmentTransaction.commit();

                        return true;
                    case R.id.item_favorito:

                        FragmentManager fm2 = getSupportFragmentManager();
                        FragmentTransaction fragmentTransaction2 = fm2.beginTransaction();

                        FragmentFavoritos  fragmentFavoritos = new FragmentFavoritos();
                        fragmentTransaction2.replace(R.id.myFragemnt, fragmentFavoritos);
                        fragmentTransaction2.commit();

                        return true;
                    case R.id.item_charola:
                        FragmentManager fm3 = getSupportFragmentManager();
                        FragmentTransaction fragmentTransaction3 = fm3.beginTransaction();

                        FragmentOrden  fragmentOrden = new FragmentOrden();
                        fragmentTransaction3.replace(R.id.myFragemnt, fragmentOrden);
                        fragmentTransaction3.commit();

                        return true;
                    case R.id.item_perfil:

                        FragmentManager fm4 = getSupportFragmentManager();
                        FragmentTransaction fragmentTransaction4 = fm4.beginTransaction();

                        FragmentPerfil  fragmentPerfil = new FragmentPerfil();
                        fragmentTransaction4.replace(R.id.myFragemnt, fragmentPerfil);
                        fragmentTransaction4.commit();


                        return true;
                }
                return false;


            }
        });*/

    @Override
    protected void onResume() {
        super.onResume();
        Log.d("CONSOLE","PAPA onResume");
        
        getApplicationContext().getViewTreeObserver()
                .addOnGlobalLayoutListener(mLayoutKeyboardVisibilityListener);


    }

    @Override
    protected void onPause() {
        super.onPause();
        Log.d("CONSOLE","PAPA onPause");
        getContentView().getViewTreeObserver()
                .removeOnGlobalLayoutListener(mLayoutKeyboardVisibilityListener);
    }

    @Override
    protected void onStart() {
        super.onStart();
        Log.d("CONSOLE","PAPA onStart");

    }




    private boolean mKeyboardVisible;
    private final ViewTreeObserver.OnGlobalLayoutListener mLayoutKeyboardVisibilityListener =
            () -> {
                final Rect rectangle = new Rect();
                final View contentView = getContentView();
                contentView.getWindowVisibleDisplayFrame(rectangle);
                int screenHeight = contentView.getRootView().getHeight();

                // r.bottom is the position above soft keypad or device button.
                // If keypad is shown, the rectangle.bottom is smaller than that before.
                int keypadHeight = screenHeight - rectangle.bottom;
                // 0.15 ratio is perhaps enough to determine keypad height.
                boolean isKeyboardNowVisible = keypadHeight > screenHeight * 0.15;

                if (mKeyboardVisible != isKeyboardNowVisible) {
                    if (isKeyboardNowVisible) {
                        onKeyboardShown();
                    } else {
                        onKeyboardHidden();
                    }
                }

                mKeyboardVisible = isKeyboardNowVisible;
            };

    private void onKeyboardShown() {
        ahBottomNavigation.hideBottomNavigation(false);
    }

    private void onKeyboardHidden() {
        ahBottomNavigation.restoreBottomNavigation(false);
    }
}

**Comment by sosite** [comment]
`getContentView()` in your situation will be main container from `R.layout.principal`.

The easiest implementation of this function is something like this:
```java
private View getContentView() {
    return findViewById(Window.ID_ANDROID_CONTENT);
}
```

**Comment by MossoIsai** [comment]
I implemented it, but it did not work, I would send you a screen shot, but by this means you can not

**Comment by sosite** [comment]
I see that you have field `frameLayoutFragment` - did you try to use it as `contentView`?

**Comment by MossoIsai** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:design="http://schemas.android.com/apk/res-auto"
    android:id="@+id/test"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:descendantFocusability="blocksDescendants">

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/myFragemnt"
        android:orientation="horizontal" />

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#ffffff"
        android:layout_gravity="bottom">
        <View
            android:layout_width="match_parent"
            android:layout_height="2dp"
            android:layout_gravity="top"/>

        <com.aurelhubert.ahbottomnavigation.AHBottomNavigation
            android:id="@+id/bottom_navigation"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom" />

    </FrameLayout>
</android.support.design.widget.CoordinatorLayout>
```

**Comment by Praveenvermatech** [comment]
The easiest implementation, Add **AndroidManifest.xml** in

`<activity android:windowSoftInputMode="adjustPan"/>`

hopefully this helps someone out. Enjoy !

**Comment by Sayooj-imvu** [comment]
adjustPan will work, but what do you do when you have a requirement to use adjustResize ?

**Comment by AhmadullahSaikat** [comment]
When keyboard appears 'adjustPan' hides the Toolbar & 'adjustResize' shows Bottombar layout. Any solution?

**Comment by RandGor** [comment]
> The easiest implementation, Add **AndroidManifest.xml** in
> 
> `<activity android:windowSoftInputMode="adjustPan"/>`
> 
> hopefully this helps someone out. Enjoy !

no, it doesn't work. It just hiding everything below keyboard that's all

**Comment by Aditya-Jaiswalgit** [comment]
> The easiest implementation, Add **AndroidManifest.xml** in
> 
> `<activity android:windowSoftInputMode="adjustPan"/>`
> 
> hopefully this helps someone out. Enjoy !

thanks it is working
