### ISSUE TITLE
The icons  not clear and blurry

### ISSUE THREAD

**Issue by mahmooddagga** [aurelhubert/ahbottomnavigation#172]
![](http://git.unitone.ps/outsourcing/Caterat_Android/uploads/c9aef31fcc6f7af430c667a910ac4276/Screenshot_20161017-140644.png)

**Comment by sosite** [comment]
If you're sure that you have proper size of this images (`24 dp` - `24 px for mdpi`, `48 px for xhdpi`, etc.) I suggest you to swap icons into SVGs.

**Comment by mahmooddagga** [comment]
thanks sosite
