### ISSUE TITLE
Without the animation of the ripples   when use viewPager.addOnPageChangeListener-->

### ISSUE THREAD

**Issue by kaiery** [aurelhubert/ahbottomnavigation#174]
**Without the animation of the ripples  when Sliding viewpage** 

viewPager.setPagingEnabled(true);
        viewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
            }
            @Override
            public void onPageSelected(int position) {
                   **bottomNavigation.setCurrentItem(position);**
            }
            @Override
            public void onPageScrollStateChanged(int state) {

```
        }
    });
```

**Comment by thousight** [comment]
I think you can try setCurrentItem(position, true);

**Comment by kaiery** [comment]
thks

**Comment by kaiery** [comment]
thks
