### ISSUE TITLE
setCurrentItem(int position, boolean useCallback) exception

### ISSUE THREAD

**Issue by Toporik** [aurelhubert/ahbottomnavigation#181]
Raise wrong function updateSmallItems() when set [titleState = ALWAYS_SHOW]. 
I think because incorrect condition:
... titleState == TitleState.SHOW_WHEN_ACTIVE <---- 

mismatch with item creation stage createItems():
... titleState == TitleState.ALWAYS_SHOW <----

**Comment by aurelhubert** [comment]
It should be fixed in the new release (2.0.1), thanks.
