### ISSUE TITLE
Align center tabIcon within bottomTab if there is no tabLabel

### ISSUE THREAD

**Issue by Crash--** [aurelhubert/ahbottomnavigation#182]
Is there already a way to do that? I know that Material Design recommendations go against it, but in my case, I really need to have bottomTab with Icons without any Label. 

If there is no way to do that, I imagine that I have to edit AHBottomNavigationItem?

**Comment by aurelhubert** [comment]
Have you tried this method?
```java
bottomNavigation.setTitleState(AHBottomNavigation.TitleState.ALWAYS_HIDE);
```

This is the result:

![screen shot 2016-11-10 at 10 21 22 am](https://cloud.githubusercontent.com/assets/4895410/20171130/987efb74-a72f-11e6-8ff3-4e51b21a1175.png)

Is it what you're looking for?

**Comment by dungnguyen10789** [comment]
if I set height of navagation bar : 
``<com.aurelhubert.ahbottomnavigation.AHBottomNavigation
        android:id="@+id/myBottomBar"
        android:layout_width="match_parent"
        android:layout_height="35dp"
        android:layout_gravity="bottom"></com.aurelhubert.ahbottomnavigation.AHBottomNavigation>``
how to set align center tabIcon ? (no label)

**Comment by aurelhubert** [comment]
@dungnguyen10789 That not the same question than @Crash-- but if you want to do that, you need to fork the library and change the height of the bottom bar. Be aware that it will break a lot of things. For now, the height of the bottom bar is defined by the Material Design guidelines.

I will close this issue for now. @Crash-- Feel free to reopen it if necessary.

**Comment by Crash--** [comment]
Thank you for your anwser @aurelhubert. I'll try it ASAP :)
