### ISSUE TITLE
How show all Text title items ?

### ISSUE THREAD

**Issue by ImanX** [aurelhubert/ahbottomnavigation#184]
hi, i want know that how show text title item and not hidden when un focused ?
one other question, how change size image Drawable item?

**Comment by aurelhubert** [comment]
You can change the visibility of the titles with:
```java
// Manage titles
bottomNavigation.setTitleState(AHBottomNavigation.TitleState.SHOW_WHEN_ACTIVE);
bottomNavigation.setTitleState(AHBottomNavigation.TitleState.ALWAYS_SHOW);
bottomNavigation.setTitleState(AHBottomNavigation.TitleState.ALWAYS_HIDE);
```
And for now, you can't change the size of the drawable (because it follows the Material Design guidelines). If you want to do that, you can fork the library.

**Comment by ImanX** [comment]
Thank for help my bro :)!

**Comment by aurelhubert** [comment]
It's since the version 2.0.0. Before, you can use `setForceTitlesDisplay(true)`

**Comment by ImanX** [comment]
tank :D

**Comment by hiddeneyes02** [comment]
It would be better if you added SHOW_WHEN_INACTIVE to avoid that the user needs to click on some item to be able to know what is in there.
