### ISSUE TITLE
Can we move the tabs to the top instead of bottom?

### ISSUE THREAD

**Issue by Jaafar-abusair** [aurelhubert/ahbottomnavigation#186]
Can we move the tabs to the top instead of bottom?

**Comment by jesse920524** [comment]
if you are using coordinatorLayout, add following property to your widget:
android:layout_gravity="top"
instead of :
android:layout_gravity="bottom"

**Comment by aurelhubert** [comment]
As @jesse920524 said, it should be working by changing the layout gravity, but be aware that the library has been developed to be in the bottom of your app, some strange behaviours could occurred.
