### ISSUE TITLE
separate fragment for each tab

### ISSUE THREAD

**Issue by MustafaTaj** [aurelhubert/ahbottomnavigation#188]
the demo in the library provide one fragment for all tabs my question is how to assign only one fragment for each bottom tab ? i tried to search google and edit the code a lots but without any result. thanx in advance

**Comment by aurelhubert** [comment]
@MustafaTaj Actually, the demo project provides one fragment per tab. You can look at the project, there is an ViewPager adapter which contains all the fragments.
