### ISSUE TITLE
TitleState.ALWAYS_HIDE not working properly in API24+

### ISSUE THREAD

**Issue by leinardi** [aurelhubert/ahbottomnavigation#190]
On API24+ the selection doesn't work properly if you set the `TitleState.ALWAYS_HIDE`:

![11z4kxnutxhzos](https://cloud.githubusercontent.com/assets/273338/20669986/2a7dc078-b577-11e6-9176-fbbbfe280ea9.gif)

The issue doesn't happens on API19 (I tested only 19, 24 & 25) of if you use `TitleState.SHOW_WHEN_ACTIVE` or `TitleState.ALWAYS_SHOW`.

This is what I am doing in the Activity:

        // Create items
        AHBottomNavigationItem item1 = new AHBottomNavigationItem("Item 1", R.drawable.ic_indicator_check);
        AHBottomNavigationItem item2 = new AHBottomNavigationItem("Item 2", R.drawable.ic_indicator_check);
        AHBottomNavigationItem item3 = new AHBottomNavigationItem("Item 3", R.drawable.ic_indicator_check);

        bottomNavigation.addItem(item1);
        bottomNavigation.addItem(item2);
        bottomNavigation.addItem(item3);
        bottomNavigation.addItem(item2);
        bottomNavigation.addItem(item3);

        bottomNavigation.setColored(true);
        bottomNavigation.setTitleState(AHBottomNavigation.TitleState.ALWAYS_HIDE);

**Comment by aurelhubert** [comment]
@leinardi Everything works fine with the Demo project on API 25. You should not use the same items multiple times (in your example: item2 & item3).

**Comment by leinardi** [comment]
Hi @aurelhubert, thank you for the quick response.
Unfortunately the issue is not related to the duplication of the items: I found the issue is there also without reusing the items and that duplication is something that I added later just for test.

With this code I'm still getting the issue with API24+:

        AHBottomNavigation bottomNavigation = (AHBottomNavigation) findViewById(R.id.bottom_navigation);

        // Create items
        AHBottomNavigationItem item1 = new AHBottomNavigationItem("Item 1", R.drawable.ic_indicator_check);
        AHBottomNavigationItem item2 = new AHBottomNavigationItem("Item 2", R.drawable.ic_indicator_check);
        AHBottomNavigationItem item3 = new AHBottomNavigationItem("Item 3", R.drawable.ic_indicator_check);
        AHBottomNavigationItem item4 = new AHBottomNavigationItem("Item 4", R.drawable.ic_indicator_check);
        AHBottomNavigationItem item5 = new AHBottomNavigationItem("Item 5", R.drawable.ic_indicator_check);

        bottomNavigation.addItem(item1);
        bottomNavigation.addItem(item2);
        bottomNavigation.addItem(item3);
        bottomNavigation.addItem(item4);
        bottomNavigation.addItem(item5);

        bottomNavigation.setTitleState(AHBottomNavigation.TitleState.ALWAYS_HIDE);

I have made a little example project that you can use to reproduce the issue: 
[issues190.zip](https://github.com/aurelhubert/ahbottomnavigation/files/618455/issues190.zip)

**Comment by aurelhubert** [comment]
Hi, thanks for your feedback. Actually, I know where this bug comes from. The problem here is that you use the same drawable resource for each of your tabs. You should use instead:

```java
AHBottomNavigationItem item1 = new AHBottomNavigationItem("Item 1", ContextCompat.getDrawable(this, R.drawable.ic_indicator_check));
AHBottomNavigationItem item2 = new AHBottomNavigationItem("Item 2", ContextCompat.getDrawable(this, R.drawable.ic_indicator_check));
AHBottomNavigationItem item3 = new AHBottomNavigationItem("Item 3", ContextCompat.getDrawable(this, R.drawable.ic_indicator_check));
AHBottomNavigationItem item4 = new AHBottomNavigationItem("Item 4", ContextCompat.getDrawable(this, R.drawable.ic_indicator_check));
AHBottomNavigationItem item5 = new AHBottomNavigationItem("Item 5", ContextCompat.getDrawable(this, R.drawable.ic_indicator_check));
```

Or use a different drawable resource for each of your tabs (which is most of the time the behavior expected).

**Comment by leinardi** [comment]
Hi @aurelhubert, I'm sorry to bring bad news but the issue happens also with different drawables:

        AHBottomNavigationItem item1 = new AHBottomNavigationItem("Item 1", R.drawable.ic_indicator_check);
        AHBottomNavigationItem item2 = new AHBottomNavigationItem("Item 2", R.drawable.ic_indicator_default);
        AHBottomNavigationItem item3 = new AHBottomNavigationItem("Item 3", R.drawable.ic_indicator_enterprise);
        AHBottomNavigationItem item4 = new AHBottomNavigationItem("Item 4", R.drawable.ic_indicator_key);

The workaround is to use the constructor that takes a Drawable instead of a @DrawableRes.
But all the constructors that are using @DrawableRes int resource are currently broken in API24+ for `TitleState.ALWAYS_HIDE`.

If you want to test yourself I've updated the sample project: 
[issues190.zip](https://github.com/aurelhubert/ahbottomnavigation/files/618516/issues190.zip)

**Comment by aurelhubert** [comment]
Alright, thanks for your investigation, there was a bug. The new version (2.0.2) should fix it (you still should not use the same drawable resource for all your items ;) ).
