### ISSUE TITLE
Is there any way to get tabs as a view?

### ISSUE THREAD

**Issue by IRMobydick** [aurelhubert/ahbottomnavigation#193]
Hi There, I'm going to use [TapTargetView](https://github.com/KeepSafe/TapTargetView) to show help box for first time, how can get tabs as views?

These ways:
`AHBottomNavigation.getChildAt(position)` - return an empty view in center-bottom of screen
`AHBottomNavigation.getChildAt(position).findViewById(R.id.bottom_navigation_small_item_icon)` - returns null
does not work!

Is there any chance to get tabs as view?

**Comment by aurelhubert** [comment]
@IRMobydick I will add a method `getViewAtPosition(int position)` in the next release (2.0.3)

**Comment by sembozdemir** [comment]
@aurelhubert are you sure it works properly. getViewAtPosition(int position) returns null because linearLayoutContainer.getChildCount() always returns 0.

```
	public View getViewAtPosition(int position) {
		if (linearLayoutContainer != null && position >= 0
				&& position < linearLayoutContainer.getChildCount()) {
			return linearLayoutContainer.getChildAt(position);
		}
		return null;
	}
```

**Comment by ing-edgar** [comment]
@aurelhubert @sembozdemir You are right, the problem is when onSizeChanged method is called. I think with a callback is good for notify to activity. 
 @Override
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        super.onSizeChanged(w, h, oldw, oldh);
        createItems();   
       callback.notifyChanged();
    }
