### ISSUE TITLE
How do switch between fragment

### ISSUE THREAD

**Issue by gkfillipus** [aurelhubert/ahbottomnavigation#194]
I am using this library its amazing library

however i am having problem switching between fragment OnTabSelected, i want to replace fragment with my own fragment e.g fragment1 Frgament2

How to do i implement that?

Thank you

**Comment by FilipeOS** [comment]
Hi there, check my issue and you will see at least a bit of the code https://github.com/aurelhubert/ahbottomnavigation/issues/183

**Comment by aurelhubert** [comment]
@gkfillipus I suggest you to take a look at the demo project, there is an example with a custom view pager (AHBottomNavigationViewPager) that helps you to manage your tabs (fragments).

**Comment by gkfillipus** [comment]
thanks @aurelhutbert i managed to get it right, i actually changed the homeFragment to my own fragments

good work
