### ISSUE TITLE
TitleState.SHOW_WHEN_ACTIVE not working with 3 tabs

### ISSUE THREAD

**Issue by ThoastProductions** [aurelhubert/ahbottomnavigation#195]
Is it by design? It's working with 2,4 and 5 tabs, but not with 3?

**Comment by aurelhubert** [comment]
Actually, the original guidelines say that we should display all titles when there are 3 items, and only the selected item title when there are more than 3 items (https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-style). The current implementation forces to display all the titles when there are only 3 items.

Is it a problem for you? The title states have been added to help people to manage the titles visibility (against the Material Design) guidelines.

**Comment by ThoastProductions** [comment]
Aah, I see. Sorry I didn't know the guidelines stated that. No problem, I thought it was a bug.

**Comment by SetareMaghari** [comment]
hi, i know the guidelines  but I need TitleState.SHOW_WHEN_ACTIVE for my three tabs, is there any way?
