### ISSUE TITLE
how to set the red dot ?

### ISSUE THREAD

**Issue by adbGitHub** [aurelhubert/ahbottomnavigation#196]
How to set the red dot, do not need to remind the number?

**Comment by tuzhenlei** [comment]
may be u can set the notification text  = ""

**Comment by adbGitHub** [comment]
i try
but can not set size of  the red dot view

**Comment by tuzhenlei** [comment]
sure , the author didn't expose the method to set the red dot size , u can change it by modify the source code, it's easy. u can download the library , then import it as a module and depend on it . Now u can change all the view size  ! And I found that most of the view size is defined in "dimens.xml" by author, u can change view size in it  conveniently . I changed the text  & icon  size ,haha !

**Comment by aurelhubert** [comment]
@adbGitHub I've chosen to limit the number of customizations, to follow as nearly possible the Material Design guidelines, but as @tuzhenlei said, feel free to fork the library and add functionalities.
