### ISSUE TITLE
Icons stay the same when using TitleState.ALWAYS_HIDE

### ISSUE THREAD

**Issue by max-david** [aurelhubert/ahbottomnavigation#197]
I've noticed that the Icons doesn't change their size when clicked when I call 
`bottomNavigation.setTitleState(AHBottomNavigation.TitleState.ALWAYS_HIDE);`

Like when using SHOW_WHEN_ACTIVE, the Icon and text size is increased when selected

It just doesn't look good (kind of buggy) and I want that my Icons use the whole space

**Comment by tuzhenlei** [comment]
u can read the source code & set the icon size and style whatever u want , it's very easy ~

**Comment by aurelhubert** [comment]
@max-david the size of the icons never change, only the titles font sizes (and the margins). If you want to add custom effects, I suggest you, as @tuzhenlei said, to fork the library & look at the code.

**Comment by RuairiOliver** [comment]
Hi,

I've forked the library but struggling to increase the size of one of the icons. 

I've increased the values in dimens.xml but it hasn't had any impact.
Is there somewhere else I should be looking?

Thanks
