### ISSUE TITLE
ahbottomnavigation is not showing in Nougat 

### ISSUE THREAD

**Issue by samirmangroliya** [aurelhubert/ahbottomnavigation#199]
i integrated this library but its not working in new version of android Nougat, Any Help ?

**Comment by aurelhubert** [comment]
I don't have any problems with the latest version of the library on Android 25. Have you tried to build the demo project?

**Comment by aurelhubert** [comment]
I close the issue for now. Please try the demo project and re-open the issue if you still have problems.
