### ISSUE TITLE
Potential crash when !(context instanceof Activity)

### ISSUE THREAD

**Issue by consp1racy** [aurelhubert/ahbottomnavigation#2]
In the helper class:

    Window window = ((Activity) view.getContext()).getWindow();

`view.getContext()` could return a `ContextThemeWrapper`. Unwrap activity object with this:

    public static Activity unwrap(Context context) {
        while (!(context instanceof Activity)) {
            ContextWrapper wrapper = (ContextWrapper) context;
            context = wrapper.getBaseContext();
        }
        return context;
    }

**Comment by aurelhubert** [comment]
@consp1racy Thanks, it will be fixed on the next release (0.1.2)
