### ISSUE TITLE
Ripple Effect

### ISSUE THREAD

**Issue by veeranath** [aurelhubert/ahbottomnavigation#200]
How can i remove the icon moving up? i need only change the color not the effect that it moves up

**Comment by aurelhubert** [comment]
@veeranath For now, it's not possible. You can change the titles state to show/hide the titles. If you hide the titles, you will not have the effect. The current implementation follow the Material Design guidelines (https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-style), but you can fork the library and change the animation.
