### ISSUE TITLE
deprecated AHBottomNavigationItem

### ISSUE THREAD

**Issue by nikhil-webmavens** [aurelhubert/ahbottomnavigation#201]
When i tried to add icons with text in Navigation, it shows AHBottomNavigationItem is deprecated.

`        itemMe = new AHBottomNavigationItem("Me", R.drawable.ic_redo, R.color.colorPrimaryDark);`

**Comment by nikhil-webmavens** [comment]
Ooops, Worked !! Thanks

**Comment by the-maux** [comment]
Best way to educate, nice one
