### ISSUE TITLE
TitleState.SHOW_WHEN_ACTIVE always show title

### ISSUE THREAD

**Issue by metsa123** [aurelhubert/ahbottomnavigation#207]
Code line: 
bottomNavigation.setTitleState(AHBottomNavigation.TitleState.SHOW_WHEN_ACTIVE);
Effect - titles in all tabs are always visible.
Code used from How to? (version with CoordinatorLayout and Activity/Fragment sections). 
Android version 4.4.2.  Manifest:  minSdkVersion 19,  targetSdkVersion 24, compileSdkVersion 24

**Comment by rhanbIT** [comment]
If you have less than 4 elements in your BottomNavigation you will always have the titles since this library follow google guide for Bottom Navigation :)

**Comment by aurelhubert** [comment]
As @rhanbIT said, this component follows the Material Design guidelines (https://material.io/guidelines/components/bottom-navigation.html). This method is already out of the scope and is here to help some users to show or hide titles for tab with 4/5 items, but if you need, you can definitely fork the library for your own needs.
