### ISSUE TITLE
custom ui

### ISSUE THREAD

**Issue by manvfx** [aurelhubert/ahbottomnavigation#209]
how to create custom ui with styles bottom navigation? 
for example: 
https://armijnvink.files.wordpress.com/2014/05/navigation.jpg

please help me with example code.
thanks

**Comment by aurelhubert** [comment]
@manvfx you can do this kind of customizations but you will have to fork the project and change a lot of stuff in the library. Maybe you should write your own library for that (don't forget that this one follows the Material Design guidelines here: https://material.io/guidelines/components/bottom-navigation.html).
