### ISSUE TITLE
Seeing 'The items list should not have more than 5 items' even though I only have 5 items

### ISSUE THREAD

**Issue by zunjae** [aurelhubert/ahbottomnavigation#21]
I think it's being called from addItems in AHBottomNavigation

    (items.size() >= MAX_ITEMS

Is this warning intentional or am I misunderstanding it?
In my opinion it'd make more sense to display this warning if I tried to add more than 5 items.

**Comment by aurelhubert** [comment]
@zunjae You're right, I've pushed a fix (it will be available on the next release).
