### ISSUE TITLE
how to set up first tab (fragment) display

### ISSUE THREAD

**Issue by manhkamen** [aurelhubert/ahbottomnavigation#211]
Hi, I am facing a problem and can't find solution.
I would like to change default tab (fragment) display depend on my data, or after update status, but after overnight, I think it's a big problem. 
```java
	Integer setFlag = getArguments().getInt("index", 0);
	/*if(itemsData!=null&& itemsData.size()!=0){
		setFlag =3;
	}*/
	if (setFlag == 0) {
		View  v = inflater.inflate(R.layout.frament_maint, container, false);
		initMainFragment(v,inflater,container);
		return v;
	} else if (setFlag == 1) {
		View v = inflater.inflate(R.layout.frament_input_by_hand,container,false);
		/*
		tbInputByHand = (TableLayout) v.findViewById(R.id.tbInputByHand);
		*/
		initInputByHand(v);
		return v;
	} else {
		View v = inflater.inflate(R.layout.fragment_transaction,container,false);
		tableLayout =(TableLayout) v.findViewById(R.id.tbTransaction);
		initTransaction(v);
		return v;
	}
```
Firstly, I tried to set flag for  getArguments().getInt("index", 0); but only default fragment load data. Then read document and find solution from internet.
Please help me. 
Thanks for your supporting.

**Comment by aurelhubert** [comment]
@manhkamen I suggest you to follow the demo project. Use `setCurrentItem(int position, boolean useCallback)` to change the current item in your *AHBottomNagivation*, set a listener for your *AHBottomNavigation* with `setOnTabSelectedListener(OnTabSelectedListener tabSelectedListener)`, and change inside the view pager current item `viewPager.setCurrentItem(position, false);`

You can check the demo project Activity here:
https://github.com/aurelhubert/ahbottomnavigation/blob/master/demo/src/main/java/com/aurelhubert/ahbottomnavigation/demo/DemoActivity.java
