### ISSUE TITLE
Selected item background color

### ISSUE THREAD

**Issue by agustinsivoplas** [aurelhubert/ahbottomnavigation#217]
It's possible to achieve this?

I have added this lines but not works:
```
bottomNavigation.setSelectedBackgroundVisible(true);
<color name="colorBottomNavigationSelectedBackground">#40000000</color>
```

![pasted image at 2017_02_17 10_01 am](https://cloud.githubusercontent.com/assets/1648539/23066738/d5a8b9fe-f4fa-11e6-8990-ebc35956c847.png)

Many thanks

All the best

**Comment by aurelhubert** [comment]
@agustinsivoplas I think there is a bug in the current version (2.0.4). I've updated the layout to show the selected background color if needed with API >= 21 in the next release (2.0.5).
