### ISSUE TITLE
2.0.5 - Regression in item click effect background since 2.0.4

### ISSUE THREAD

**Issue by tbsandee** [aurelhubert/ahbottomnavigation#222]
I have an nVidia shield, API 24 device that exhibits a problem with 2.0.5 but not 2.0.4. I'm pretty sure it stems from changes to the `item_background.xml` drawable used in place of simple `?selectableItemDrawable`.

The problem is that when switching between tabs, the pressed ring of the selectable drawable doesn't always go transparent after clicking and a remainder artifact is left behind. I've attached a screenshot. Strangely I've only see it happen on the first item in the bottombar.

Reverting to 2.0.4 fixes the issue every time.

![artifact](https://cloud.githubusercontent.com/assets/1088116/23516505/0c9c387c-ff33-11e6-87fc-f650d982f65b.png)

**Comment by kenumir** [comment]
+1

**Comment by aurelhubert** [comment]
Thanks, I will fix that in the next release (2.0.6).

**Comment by tbsandee** [comment]
awesome, thx so much! fix verified for me.
