### ISSUE TITLE
XML Size issue

### ISSUE THREAD

**Issue by gopicg** [aurelhubert/ahbottomnavigation#224]
I have add menu through XML ,But you have restrict up-to 5 ,min 3 
Can you expand the limit ?

W/AHBottomNavigation: The items list should have at least 3 items
W/AHBottomNavigation: The items list should not have more than 5 items

**Comment by aurelhubert** [comment]
The library currently tries to follow the [Material Design guidelines,](https://material.io/guidelines/components/bottom-navigation.html) which recommends to use this component when you have between 3 to 5 items to display. If you want a more custom behavior, I suggest you to fork and modify the libray.
