### ISSUE TITLE
No Animation on tabs change

### ISSUE THREAD

**Issue by dyckster** [aurelhubert/ahbottomnavigation#227]
Hello! Greate library, one question though, is it possible to disable sliding animation between viewpager items?

**Comment by aurelhubert** [comment]
I suggest you to use this method `viewPager.setCurrentItem(position, false);` to set the current item of your ViewPager without animation. If you want to block the sliding touch event on the ViewPager, you can use the class `AHBottomNavigationViewPager`, which is included in the library.
