### ISSUE TITLE
could you provide a mothod to stop the scale animation with the title when tab selected?

### ISSUE THREAD

**Issue by canhuah** [aurelhubert/ahbottomnavigation#228]
could you provide a mothod to stop the scale animation with the title when tab selected?

**Comment by aurelhubert** [comment]
The library currently follows the [Material Design Guidelines](https://material.io/guidelines/components/bottom-navigation.html). If you want to disable the animations, I suggest you to fork the library and remove the animation that you don't want.

**Comment by akashMehta-STL** [comment]
@canhuah I found one jack for this solution you can override 4 dimension resource and update that. You can override the following dimensions.
    <dimen name="bottom_navigation_text_size_active">12sp</dimen>
    <dimen name="bottom_navigation_text_size_inactive">12sp</dimen>
    <dimen name="bottom_navigation_margin_top_active">6dp</dimen>
    <dimen name="bottom_navigation_margin_top_inactive">6dp</dimen>

In this repo, @aurelhubert is doing animation for text size and bottom navigation margin so if will make this values same then animation will not affect.

**Comment by akashMehta-STL** [comment]
@canhuah I found one jack for this solution you can override 4 dimension resource and update that. You can override the following dimensions.
```
   <dimen name="bottom_navigation_text_size_active">12sp</dimen>
   <dimen name="bottom_navigation_text_size_inactive">12sp</dimen>
   <dimen name="bottom_navigation_margin_top_active">6dp</dimen>
   <dimen name="bottom_navigation_margin_top_inactive">6dp</dimen>
```
In this repo, @aurelhubert is doing animation for text size and bottom navigation margin so if we make this values same then the animation will not affect.

**Comment by akashmehta** [comment]
@canhuah I found one jack for this problem you can override 6 dimension resource and update that. You can override the following dimensions.
```
   <dimen name="bottom_navigation_text_size_active">11sp</dimen>
   <dimen name="bottom_navigation_text_size_inactive">11sp</dimen>

   <dimen name="bottom_navigation_text_size_forced_active">11sp</dimen>
   <dimen name="bottom_navigation_text_size_forced_inactive">11sp</dimen>

   <dimen name="bottom_navigation_margin_top_active">6dp</dimen>
   <dimen name="bottom_navigation_margin_top_inactive">6dp</dimen>
```
In this repo, @aurelhubert is doing animation for text size and bottom navigation margin so if we make this values same then the animation will not affect.

**Comment by imran-samed** [comment]
@canhuah Awesome, its working.
