### ISSUE TITLE
Set current item without fire the on click event

### ISSUE THREAD

**Issue by agustinsivoplas** [aurelhubert/ahbottomnavigation#229]
I would like to know if this behaviour is possible.

I have a web view and a navigation button (5 items (home, account, etc) which load a page in webview), the problem is when user is in home page, he can navigate to account page without click in account item, so, i would like to set the current item as account. I tried with setCurrentItem but it's seems like a onclick event and reload the page again.

Many thanks

All the best

Agustin

**Comment by aurelhubert** [comment]
Have you tried `setCurrentItem(int position, boolean useCallback)` with `useCallback`to **false**?

**Comment by agustinsivoplas** [comment]
Yes, I have discovered my error, I had override the method OnTabSelectedListener and always return false. My bad.
