### ISSUE TITLE
Notification number bigger than 10 don't appear.

### ISSUE THREAD

**Issue by juanpaternina** [aurelhubert/ahbottomnavigation#23]
Hello.

Working with the library, at the moment of my notification badge is greater than 10. Don't appear any number. Is this a bug? or improvement. 

Tested on Android Lollipop - Nexus 6.

Implementation:

`bottomNavigation.setNotification(idChat, response.body().getData().size());`
`bottomNavigation.setNotification(1, 16);`

**Comment by aurelhubert** [comment]
@juanpaternina I think you have inverted the number of notifications and the tab position:

`public void setNotification(int nbNotification, int itemPosition)`

**Comment by juanpaternina** [comment]
mmm yes you're right! Thanks you
