### ISSUE TITLE
AHBottomNavigation make height smaller than current

### ISSUE THREAD

**Issue by MostafaAnter** [aurelhubert/ahbottomnavigation#230]
i want to make height smaller and make icon inside view scale to suite my custom height there is any way to do this, thanks in advanced

**Comment by aurelhubert** [comment]
The library currently follows the [Material Design Guidelines](https://material.io/guidelines/components/bottom-navigation.html). If you want to change the height of the AHBottomNavigation, I suggest you to fork the library. Remember that it will probably break some animations.
