### ISSUE TITLE
Icon and background colors

### ISSUE THREAD

**Issue by debjitk** [aurelhubert/ahbottomnavigation#238]
I am confused.

What does these do ...

setColored ?
setForceTint ?

setAccentColor ?
setInactiveColor ?

setColoredModeColors ?

There seems to a combination to make these work ? Whats the puzzle please.

**Comment by aurelhubert** [comment]
`setColored`: Define if we use the colors of the tab items. For example, the tab item color can be defined here `new AHBottomNavigationItem(R.string.tab_1, R.drawable.ic_apps_black_24dp, R.color.color_tab_1);`

`setForceTint`: You can force the tint if you have a problem with the tabs icons color.

`setAccentColor`: the color for the the icon & title when the tab is selected

`setInactiveColor`: the color use for the icon & title when the tab is inactive

`setColoredModeColors`: Like the 2 previous methods, but used when we set `setColored` to true.

**Comment by lectricas** [comment]
@aurelhubert can you make a good example of how to use all this parameters.(or at lease good docs) It would be a lot easier for everyone!
