### ISSUE TITLE
Want to set a tab disable.

### ISSUE THREAD

**Issue by phapli** [aurelhubert/ahbottomnavigation#239]
I found:
bottomNavigation.setAccentColor(...);
bottomNavigation.setInactiveColor(...);

And I think it is color for tab was selected and another. But i want another state: disable

like this: https://cdn-images-1.medium.com/max/1600/1*M6HU7jlyQhmV8CjFcKdQhw.png
It means you cannot touch or select this tab. 

So, plz guide me how to achieve this state, or not?
Thanks

**Comment by aurelhubert** [comment]
It will be added in the next release. 3 new methods in AHBottomNavigation:
```java
public void enableItemAtPosition(int position)
public void disableItemAtPosition(int position)
public void setItemDisableColor(@ColorInt int itemDisableColor)
```
Render with 3 items:
![disable_3](https://user-images.githubusercontent.com/4895410/29610380-4f3d0b52-87fa-11e7-9215-0bfc09727795.png)

Render with 5 items:
![disable_5](https://user-images.githubusercontent.com/4895410/29610385-5125733c-87fa-11e7-99c5-067a4b8a8261.png)
