### ISSUE TITLE
How to remove notification at run time?

### ISSUE THREAD

**Issue by IMMETHI** [aurelhubert/ahbottomnavigation#248]

**Comment by FlorentAnders** [comment]
Asking myself the same question. Do we oversee something?

**Comment by FlorentAnders** [comment]
Send a "" as the notification content.

**Comment by aurelhubert** [comment]
As @FlorentAnders said, use:
```java
int yourTab = 0;
bottomNavigation.setNotification("", yourTab);
```

**Comment by rituapplocum** [comment]
> Send a "" as the notification content.

still the badge is displaying with 0 value, how can I remove the badge as well
