### ISSUE TITLE
Sizing problems

### ISSUE THREAD

**Issue by FlorentAnders** [aurelhubert/ahbottomnavigation#250]
Hello!

I created my own fork of your library but had some issues:

1. I was able to make the icons a little bigger as I wanted.
2. I wanted to make the bar center the icons when no title is being shown, because they aren't centered anymore. I also tried to make the bar a little smaller, they were even more pushed to the bottom. Removing and modifying paddings in the ImageViews inside the layouts didn't work out.
3. I wanted the four items to fill out the whole screen and be centered across the whole screen, this isn't the case at the moment as they are a little too close to each other and a little too far from the sides.

Still was I really happy to implement it as hiding and restoring for example works absolutely great! Thanks for this library and your hard work!

Do you see any solutions for my problems?
Thanks!

**Comment by aurelhubert** [comment]
Be careful, the items have a min & max width. There are a lot of dimensions for the views inside the bottom navigation. Try to check the file `res/values/dimens.xml` if you want to understand how everything works. If you have any others questions, feel free to ask.
