### ISSUE TITLE
How to redirect like intent to spesific position with fragment?

### ISSUE THREAD

**Issue by wasitaanggara** [aurelhubert/ahbottomnavigation#251]
nice plugin and great works man, but i have issue how to redirect to spesific position with fragment inside it?   
Example : Setup bottomnavigation on MainActivity.java with fragmentTransaction(Position 1) and then i have other activity ChartTransactionActivity, after ChartTransactionActivity complete i wanna redirect back into MainActivity with currentPosition FragmentTransaction?
If i used intent to MainActivity its always on default position 0.
Intent intent = new Intent(ChartTransactionActivity.this, MainActivity.class);
startActivity(intent);
Sorry for my bad english.

Best Regards

**Comment by aurelhubert** [comment]
I'm not sure to understand your problem. You can use the next method to change the current tab:
```
setCurrentItem(int position, boolean useCallback)
```
Take a look at the Demo project if you need. If you want to manage a stack of fragments per each tab, I suggest you to manage it like you'll usually do.
