### ISSUE TITLE
bottomBar.setCurrentItem(pos, true) not highlighting the bottom menu item.

### ISSUE THREAD

**Issue by SanPinto** [aurelhubert/ahbottomnavigation#256]
When I launch the app, I'm manually calling setCurrentItem() method of AHBottomNavigation class to highlight the bottom menu item. On debugging, I found that call goes inside and it does call setCurrentItem() method, but it is not highlighting the bottom menu item. But when i click on the item, it highlights the item. What is wrong ?

**Comment by aurelhubert** [comment]
The problem comes probably from your implementation, I can't reproduce it in the Demo project. Be sure to add your `AHBottomNavigationItem` before calling `setCurrentItem` on your `AHBottomNavigation` object.
