### ISSUE TITLE
Is hidden() function return Nullpointer Exception;

### ISSUE THREAD

**Issue by HessamMosleh** [aurelhubert/ahbottomnavigation#259]
i try to use isHidden function for a condition but return
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.aurelhubert.ahbottomnavigation.AHBottomNavigationBehavior.isHidden()' on a null object reference

**Comment by aurelhubert** [comment]
The problem here is that you probably call the method too soon. I will add a condition to check if the AHBottomNavigationBehavior is already created, but try to check if everything is okay on your side.
