### ISSUE TITLE
BottomNavigation Stays Hidden after Fragment Switch

### ISSUE THREAD

**Issue by bhargavgit** [aurelhubert/ahbottomnavigation#26]
I have a Fragment with a RecyclerView. As I Scroll Down as desired the bottom navigation bar is hidden. In this state - if I click on an Item in my recyclerView - Its replaces the Fragment with a new Fragment with Item Detail. This new Fragment does not have Scrollable content and the BottomNavigation stays hidden and cannot be accessed.

**Comment by NikolaDespotoski** [comment]
@aurelhubert  Head to updated [BottomNavigationBehavior](https://github.com/NikolaDespotoski/BottomNavigationLayout/blob/master/bottomnavigationlayout/src/main/java/despotoski/nikola/github/com/bottomnavigationlayout/BottomNavigationBehavior.java). There is convenient method that restores the bottom navigation translation to zero, which solves this issue.

**Comment by aurelhubert** [comment]
I've added a method to restore the bottom navigation: restoreBottomNavigation()
If you have a better way to do it (an automatic way), feel free to submit a pull request!
