### ISSUE TITLE
How do I use my own selecter icons on bottom navigation

### ISSUE THREAD

**Issue by SherlockOy** [aurelhubert/ahbottomnavigation#261]
I've read through your code and found that you have an judment in the `AHBottomNavigationItem` 

```java
public Drawable getDrawable(Context context) {
    if (drawableRes != 0) {
      try {
        return VectorDrawableCompat.create(context.getResources(), drawableRes, null);
      }catch (Resources.NotFoundException e){
        return ContextCompat.getDrawable(context, drawableRes);
      }
    }
    return drawable;
  }
```
And I assumed that those code is for users to use their own `Drawable`s to display, yet I tried very hard this afternoon and failed to make that happen, all my Drawable seems to be converted into the VectorDrawable, and looked solid. 

Is there a way to use my own Drawable in Res directory? Appreciate.

BTW, Great library.

**Comment by aurelhubert** [comment]
I'm not sure to understand exactly your problem but I've just updated this part of the code. You should be able to use drawable (jpg/png/xml vector/xml selector...) in the next release.

**Comment by bdavid68** [comment]
@SherlockOy It's implemented here.

[https://github.com/bdavid68/ahbottomnavigation/tree/selected-icon](url)

// Force to tint the drawable (useful for font with icon for example)
// false : ignore tint color, apply selected icon
// true : apply tint color, ignore selected icon
bottomNavigation.setForceTint(true);

If you set forceTint as *false*, tint colour won't be applied on your icons so you can use your own Drawables for normal and selected states.

**Comment by SherlockOy** [comment]
@bdavid68 Sorry but not able to open the link.

**Comment by HeshamMorsy** [comment]
@SherlockOy did you find any solution to set your own drawables other than using specific colors by setColoredModeColors method?

**Comment by piotrkst** [comment]
Declare your selector in res/drawables (f.ex. menu_xyz_selector) and use selector as a item's drawable resource:

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/ic_menu_xyz_selected" android:state_selected="true"/>
    <item android:drawable="@drawable/ic_menu_xyz_unselected" android:state_selected="false"/>
</selector>


val menuItem = AHBottomNavigationItem(
                    resources.getString(R.string.menu_xyz_title),
                    ContextCompat.getDrawable(this, R.drawable.menu_xyz_selector),
                    ContextCompat.getColor(this, R.color.colorPrimary))

bottomNavigationView.addItem(menuItem)
           
```
