### ISSUE TITLE
Null pointer Excption on setTitleState

### ISSUE THREAD

**Issue by ankur1486** [aurelhubert/ahbottomnavigation#262]
Attempt to invoke virtual method 'void com.aurelhubert.ahbottomnavigation.AHBottomNavigation.setTitleState(com.aurelhubert.ahbottomnavigation.AHBottomNavigation$TitleState)' on a null object reference

clearly bottombar is null have added a check .
Hope it should not come now but still if its something internal issue please let us know

**Comment by aurelhubert** [comment]
Where do you call the method `setTitleState`? For now, I think the problem comes from your implementation. If not, please give me more details to look at the problem, thank you.
