### ISSUE TITLE
Back on top on menu item click

### ISSUE THREAD

**Issue by pesseyjulien** [aurelhubert/ahbottomnavigation#265]
Hi,

Is there a way to implement this behavior using this library ?

Thanks in advance,
Julien

**Comment by FnR2** [comment]
can you explain a little bit more your question?

**Comment by pesseyjulien** [comment]
Well, if I click on the icon/text of a menu's item, it will scroll up to top. Exactly like on the facebook app for example.

**Comment by st-f** [comment]
Seconding. Would really like to have that feature.

**Comment by st-f** [comment]
Basically it's about adding on item click listener, allowing to know when the user tap on a menu item (this is different than a selection change)

**Comment by st-f** [comment]
I guess this:
@pesseyjulien this works for me:

bottomNavigation.getViewAtPosition(0).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Log.i(LOG_TAG, "");
            }
        });

**Comment by aurelhubert** [comment]
You can manage it manually with this listener
```java
bottomNavigation.setOnTabSelectedListener(new AHBottomNavigation.OnTabSelectedListener() {
	@Override
	public boolean onTabSelected(final int position, final boolean wasSelected) {
		// TODO: Check here if the tab was already selected. If true, scroll to the top of your recycler view
		return true;
	}
});
```
