### ISSUE TITLE
SVG image resource caused error on API 17

### ISSUE THREAD

**Issue by GitHubMurt** [aurelhubert/ahbottomnavigation#267]
Hey, 
I use 

When I use 
`AHBottomNavigationItem itemHome = new AHBottomNavigationItem("Home", R.drawable.ic_home_return_selector);` 
 I get error that 

> ViewPort.width have to be  > 0

That drawable resource (R.drawable.ic_home_return), that is in fact **_xml selector_** that consist two **_"items drawable=..."_** ,  whereas those drawables are VectorDrawables.

The reason why library throws error, Is some malfunction in method DrawableUtils.getDrawable()
However I found a solution.
If you will set drawables inside **AHBottomNavigation** this manner
`imageView.**setImageResource**(item.itemRes);`
instead of creating drawable and then setting it like (it is currently)
`icon.**setImageDrawable**(item.getDrawable(context))`

the error will not happend

You may for example try to catch an error in 
`icon.**setImageDrawable**(item.getDrawable(context))` , and then try do set raw IconRes (without using ting) `imageView.**setImageResource**(item.itemRes);`

I use buildToolsVersion "26.0.0"

**Comment by aurelhubert** [comment]
I've found another solution, I use in `AHBottomNavigationItem.java` the next method to get the drawable:
```java
return AppCompatResources.getDrawable(context, drawableRes);
```
instead of:
```java
return VectorDrawableCompat.create(context.getResources(), drawableRes, null);
```

The only thing you have to think about if the compatibility with Android < 21 (Lollipop). In that case, you should add:
```java
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
	AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
}
```
in your Application class.

I will add this change in the next release.
