### ISSUE TITLE
Not full width

### ISSUE THREAD

**Issue by charzone95** [aurelhubert/ahbottomnavigation#273]
Hi.
I'm switching from official Bottom Navigation View to this library.
But I notice that when using this library, the width is not the same as the original library
Did I miss something?

Official library:
![official](https://user-images.githubusercontent.com/9084969/28903440-129e8228-782f-11e7-93cc-b000feb7a884.png)

AHBottomNavigation
![ahbottomnav](https://user-images.githubusercontent.com/9084969/28903444-1abf2066-782f-11e7-9a94-424808158fd8.png)

**Comment by aurelhubert** [comment]
I will need more details to help you. The library should match the parent width. I close the issue for now, feel free to reopen it if you have more details
