### ISSUE TITLE
addItem more then 5

### ISSUE THREAD

**Issue by ubihacks** [aurelhubert/ahbottomnavigation#277]
Is there limits  of  **5 item** ??
it working fine with 5 item as i go for 6 the app start crashing  
any suggestion for this problem??

**Comment by aurelhubert** [comment]
Yes, there is a limit to 5 items (three to five items / https://material.io/guidelines/components/bottom-navigation.html), but thank you for your feedback. I will fix the crash and I suggest you to use another pattern if you want to display at least six items.

**Comment by deshario** [comment]
Can we add more than 5 items from R.menu.menufile nowdays .... Does this feature was added or not ?
