### ISSUE TITLE
about right to left items in ahbottomnavigation

### ISSUE THREAD

**Issue by shahrzadKeivan** [aurelhubert/ahbottomnavigation#281]
Hi, thank you for your  library . I am new in android , can you help me? Is there a way to get items right to left? And the information inside it does not disrupt its display, i use   bottomNavigation.setCurrentItem(3);
but data has left to right, 
and question2 : Can I use Activity instead of a fragment?

**Comment by osmanalsikh93** [comment]
Hi. 
just set your app Local to "ar" and in manifests add android:supportsRtl="true"

**Comment by aurelhubert** [comment]
And for the second question: you can't use a specific activity for each tab, please use fragments or custom views.
