### ISSUE TITLE
How to add border foreach bottom tab?

### ISSUE THREAD

**Issue by diennguyentien** [aurelhubert/ahbottomnavigation#282]
Hi all, I am newbie in android , can you help me? 
![image](https://user-images.githubusercontent.com/26664425/29954467-2853015e-8f02-11e7-856f-d932c175ec77.png)
I want to add border red foreach tab, and border bottom selected, but I don't know how to do it.

**Comment by jahirfiquitiva** [comment]
If I'm not wrong, the library has been created to match/follow [Material Design guidelines](https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-specs) and bottom navigation actions are not supposed to have borders.

**Comment by aurelhubert** [comment]
As @jahirfiquitiva said, this library aims to create a bottom navigation component following the Material Design Guidelines. Feel free to fork the library.
