### ISSUE TITLE
Add Dividers

### ISSUE THREAD

**Issue by nsuthar20** [aurelhubert/ahbottomnavigation#283]
How can I add dividers in between of bottom navigation's tabs?

**Comment by jahirfiquitiva** [comment]
If I'm not wrong, the library has been created to match/follow [Material Design guidelines](https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-specs) and dividers are not supposed to be part of bottom navigation.

**Comment by Rainer-Lang** [comment]
@aurelhubert Close this issue or are you open for a PR?

**Comment by aurelhubert** [comment]
I prefer close the issue to avoid too many unused functionalities, but feel free to fork the library 👍
