### ISSUE TITLE
How maintain back stack for user selected bottom navigation ??

### ISSUE THREAD

**Issue by SubhashGaikwad** [aurelhubert/ahbottomnavigation#287]

**Comment by fogx** [comment]
You will probably have to maintain it yourself, although you should not be doing it in the first place ->
> On Android, the Back button does not navigate between bottom navigation bar views.
> https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-style

**Comment by aurelhubert** [comment]
You can write it with a stack of fragments, but try to follow the Material Design Guidelines.
