### ISSUE TITLE
Badge custom xml drawable

### ISSUE THREAD

**Issue by naivekook** [aurelhubert/ahbottomnavigation#289]
I want to use custom xml drawable with stroke, but it looks ugly.
Seems like I should set padding equals stroke width, but how can i do this?
(padding in xml doesn't work)

![screenshot_20171009-055405_](https://user-images.githubusercontent.com/1501831/31339440-8b98ceca-ad0b-11e7-8039-7ba754e942c1.png)

**Comment by aurelhubert** [comment]
You can just add an drawable resource (named `notification_background.xml`) like that:

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="@color/colorBottomNavigationNotification" />
    <corners android:radius="@dimen/bottom_navigation_notification_radius" />
    <stroke android:color="YOUR COLOR" android:width="2dp"/>
</shape>
```
