### ISSUE TITLE
remove shadow or elevation top 

### ISSUE THREAD

**Issue by juanlabrador** [aurelhubert/ahbottomnavigation#29]
Thanks

**Comment by aurelhubert** [comment]
@juanlabrador What do you want exactly? The shadow is in the Material Guidelines, can you explain more in details? Thanks.

**Comment by juanlabrador** [comment]
I know, and I do not criticize anything. I'm just using the bar, but do not need the higher elevation, have tried to superimpose the view that I use to see if you do not dial, and does not give. @aurelhubert

**Comment by aurelhubert** [comment]
I've added a method: setUseElevation(boolean useElevation)
