### ISSUE TITLE
setCurrentItem doesn't work

### ISSUE THREAD

**Issue by aalap03** [aurelhubert/ahbottomnavigation#290]
**Current Behaviour:** I have 5 items in bottom navigation view, by default 1st item is coloured (Active or enable) when user comes here first. 

**Goal**: In one scenario user can come to the app from notification and lands on 4th fragment. I want to make 4th fragment (3rd position in bottom view) coloured.

**Issue**: I tried using `setCurrentItem(3)` but still shows first item coloured.  
Also tried `bottomNavigation.enableItemAtPosition(3);` but same result. 

How to make this work ?

**Comment by Ayesha-Fazal** [comment]
i have the same issue here

**Comment by aalap03** [comment]
Has anyone found its solution.. ??

**Comment by aalap03** [comment]
I am still trying to solve it and reading method descriptions and tries these combinations but still not impact. 
Image is there just to show what I need and what is happening.

            bottomNavigation.enableItemAtPosition(SECURITY);
            // true gives me bigger icon (as selected) but not the color which I want, colour is still on first item.
            bottomNavigation.setCurrentItem(SECURITY, true);

            bottomNavigation.setAccentColor(ContextCompat.getColor(this, R.color.colorPrimary));
            bottomNavigation.setInactiveColor(ContextCompat.getColor(this, R.color.black));

            bottomNavigation.refresh();
            bottomNavigation.restoreBottomNavigation();

![screen shot 2017-11-01 at 17 04 41](https://user-images.githubusercontent.com/12421219/32297832-d76f9f4a-bf26-11e7-818a-79325e70e579.png)

**Comment by aurelhubert** [comment]
Be sure to call `setCurrentItem()` at the right moment. In the demo project, if you add `bottomNavigation.setCurrentItem(2);` at the end of `initUI()`, everything works fine.
