### ISSUE TITLE
Change title font family

### ISSUE THREAD

**Issue by chillsweet** [aurelhubert/ahbottomnavigation#293]
Amazing library!
How could I change font family of title ?

**Comment by SsKarthi** [comment]
Same problem for me also!..

**Comment by Fatimamostafa** [comment]
Anyone sort the issue?

**Comment by SavitskiyA** [comment]
me too

**Comment by aurelhubert** [comment]
What about `setTitleTypeface()`? ;)

**Comment by Fatimamostafa** [comment]
Yes! 
I did actually found the solution a bit later after asking the question. Sorry forgot to mention that! :(
