### ISSUE TITLE
IndexOutofBound Exception

### ISSUE THREAD

**Issue by anderscheow** [aurelhubert/ahbottomnavigation#296]
<img width="1077" alt="screen shot 2017-10-23 at 3 35 18 pm" src="https://user-images.githubusercontent.com/11788504/31877148-f3ec7132-b807-11e7-8ff3-691011fdddd4.png">
Although only one device has this issue, just trying to figure out what is happening

**Comment by aurelhubert** [comment]
That's really strange, I don't think the problem comes from the library itself. Have you checked if you do anything with the number of items in your bottom navigation?
I close the issue for now, but feel free to reopen it if you have more details.
