### ISSUE TITLE
Not showing views

### ISSUE THREAD

**Issue by PublicStaticVoidSasha** [aurelhubert/ahbottomnavigation#297]
I really liked the library, but it doesn't seem to work correctly on the Samsung Galaxy s7. The problem is with displaying the items in the navigation. They are just not there. It works perfectly on other devices, but not on this one. Can you please help me?
Thank you.

**Comment by aurelhubert** [comment]
Do you have any other details? That's seems very weird.
I close the issue for now, but feel free to reopen it if needed.

**Comment by sbongiz** [comment]
I have the same problem, the code doesn't trigger any exception so it's difficult to give you more information. It works for other devices but doesn't work for Samsung Galaxy s7.
Do you have news about it? 
Thank you.
