### ISSUE TITLE
getViewAtPosition method return null

### ISSUE THREAD

**Issue by pblinux** [aurelhubert/ahbottomnavigation#305]
Hi! First, this is an awesome lib.
I have a problem trying to get the view of the elements, getViewAtPosition(position) always return null.

**Comment by aurelhubert** [comment]
Try to check that when you call this method, everything is correctly implemented. I've have tried on the demo project and it works. You can provide more details if you want.

**Comment by cfranchella** [comment]
@aurelhubert Can you provide me an example on how to use it? i'm always getting null and it would be really helpful to be able to use getViewAtPosition Method. Thanks!
