### ISSUE TITLE
SetCurrentItem without executing setOnTabSelectedListener

### ISSUE THREAD

**Issue by abraham28s** [aurelhubert/ahbottomnavigation#307]
When I create a new activity I like to SET the SELECTED Item programmatically but without executing the setOnTabSelectedListener in order to only show the item in the selected style.
Is there any way possible to do this?

**Comment by aurelhubert** [comment]
Please use the method `setCurrentItem(int position, boolean useCallback)` with `useCallBack` to `false`

**Comment by collinpreston** [comment]
This was helpful for when I could not get the active button color to change.  I needed to set the navigator's current item within the OnClick method.  By doing this I was able to make sure that the color of the selected icon changed correctly.  Using the setCurrentItem() method without the useCallBack parameter set to false was causing my app to crash.
