### ISSUE TITLE
Item becomes clickthrough when disabled

### ISSUE THREAD

**Issue by tingyik90** [aurelhubert/ahbottomnavigation#311]
As per title, when a item is disabled via `disableItemAtPosition(int position)`, the item becomes clickthrough. I have a recyclerview behind the bottomnavigation and it is receiving the click instead.

P.S. Hi @aurelhubert , just want to say thank you for this awesome library!

**Comment by aurelhubert** [comment]
Fixed in 2.2.0, thanks.
