### ISSUE TITLE
Failed to display JPG files on NavigationItem

### ISSUE THREAD

**Issue by cwliu** [aurelhubert/ahbottomnavigation#312]
I found there might be an issue when we use the jpg file, it's just displayed as a square with the accent colour, but I expect that the JPG image should be displayed properly. my testing code is as below: 

```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {

        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val bottomNavigation = findViewById<View>(R.id.bottom_navigation) as AHBottomNavigation
        // "https://www.freelancer.com/ppic/107492233/logo/25961105/profile_logo_25961105.jpg"
        val item1 = AHBottomNavigationItem("Account", R.drawable.profile_logo_25961105)
        bottomNavigation.addItem(item1)
    }
}
```
Observed result:
![image](https://user-images.githubusercontent.com/1084330/34747979-9de8a13c-f5ee-11e7-9793-de7785236332.png)

Expected result: 
![image](https://user-images.githubusercontent.com/1084330/34747966-8fc820e6-f5ee-11e7-9b76-0405230d1393.png)

Affected version: 2.1.0

**Comment by aurelhubert** [comment]
Thank you for the feedback. I think that's the expected behavior. The library follow the guidelines which say that we have to display icons (not pictures) for the tabs. You can fork the library and remove the part of the code which add a color on the icon if you need.
