### ISSUE TITLE
NavBar not showing if it's hidden and next tab is shown

### ISSUE THREAD

**Issue by vanpana** [aurelhubert/ahbottomnavigation#316]
I'm using navigation.setBehaviorTranslationEnabled(true) when setting up the navbar and the bug looks like this:
![ezgif-5-7f9af66c16](https://user-images.githubusercontent.com/13353799/35231594-e8f34efe-ffa1-11e7-8e61-c06bc6785306.gif)

**Comment by easycheese** [comment]
@vanpana Looks like you have some custom disappear functionality that is unrelated to the library code

**Comment by vanpana** [comment]
I wasn't using anything but the library.

**Comment by vanpana** [comment]
I fixed it by using the nav bar as static and calling reveal on tab change.
