### ISSUE TITLE
Mixing version issue?

### ISSUE THREAD

**Issue by anta40** [aurelhubert/ahbottomnavigation#319]
This is the content of my build.gradle
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "app.devbyzero.net.bottomnavdemo"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}
```

The code only consists of 1 Activity, and it compiled fine. Now, adding this part:
`implementation 'com.aurelhubert:ahbottomnavigation:2.1.0'`

Will cause this error message:
> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 26.1.0, 25.3.1. Examples include.... 

I'm using Android Studio 3.0.1

**Comment by taibuiSW** [comment]
ahbottomnavigation:2.1.0 seems to use android.support v25.3.1 library. I recommend switching to newest version 2.2.0 (implementation 'com.aurelhubert:ahbottomnavigation:2.2.0')

**Comment by anta40** [comment]
I see. It works. Closed, then :)
