### ISSUE TITLE
Nav Tab Translation Behavior only works for RecyclerViews for some reason

### ISSUE THREAD

**Issue by DaveNOTDavid** [aurelhubert/ahbottomnavigation#347]
Based on [Google's bottom navigation guidelines](https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-behavior), they suggest that we translate the bottom nav tabs (hide it when scrolling downwards, and view when upwards), and this third-party library, AHBottomNavigation, seems to be one of the few libraries that hides and views the tabs accordingly.

However, I was wondering why translation doesn't work for scrollable views (ScrollViews, ListViews, but not a RecyclerView) in a fragment container? Did anyone else experience this issue?

**Comment by TurKurT656** [comment]
yes i'm facing the same issue. when i use recyclerview there isn't a problem. but for scrollview layouts it doesn't behave correctly.
so what is the solution?
