### ISSUE TITLE
change the tab on swipe

### ISSUE THREAD

**Issue by tank777** [aurelhubert/ahbottomnavigation#369]
how can we change the tab when user swipe left or right?

**Comment by jahirfiquitiva** [comment]
You should use a `ViewPager` for that. It has nothing to do with the library. Also, Material Design guidelines advice not to do that: you should use a `TabLayout` instead

**Comment by tank777** [comment]
@jahirfiquitiva Thank you but I got the solution for that. I have used the "AHBottomNavigationViewPager" and set the setPagingEnabled(true).
