### ISSUE TITLE
First fragment only shown when its tab is reselected

### ISSUE THREAD

**Issue by Deandrew007** [aurelhubert/ahbottomnavigation#372]
Hey, lovely lib. My first fragment isn't visible unless another tab is clicked, then reselect the first tab or the first tab is clicked twice. Which is when the fragment is shown. Any possible suggestions?

**Comment by Deandrew007** [comment]
Here's a snippet of my code.

`
 bottomNavigationBar.setCurrentItem(0);
 bottomNavigationBar.setOnTabSelectedListener((position, wasSelected) -> {
            
            if (position == SHOP_FRAGMENT)
            {
                getSupportFragmentManager().beginTransaction().replace(R.id.frame_container, new ShopFragment()).commit();
            }
            else if (position == MESSAGES_FRAGMENT)
            {
                getSupportFragmentManager().beginTransaction().replace(R.id.frame_container, new MessagesFragment()).commit();
            }
            else if (position == PROFILE_FRAGMENT)
            {
                getSupportFragmentManager().beginTransaction().replace(R.id.frame_container, new ProfileFragment()).commit();
            }
            return true;
        });`

**Comment by jahirfiquitiva** [comment]
I haven't tested but I think putting `bottomNavigationBar.setCurrentItem(0);` after setting the listener, _should_ work.

Like so:
```java
bottomNavigationBar.setOnTabSelectedListener((position, wasSelected) -> {
	...
});
bottomNavigationBar.setCurrentItem(0);
```

As a suggestion, when posting multiple lines of code wrap it like this:
<pre>
<code>
```java
System.out.println("Hello, World!");
```
</code>
</pre>

**Comment by Deandrew007** [comment]
Your solution was a fix. Thanks a lot and also for the suggestion.
