### ISSUE TITLE
android.app.FragmentManager depracated

### ISSUE THREAD

**Issue by TaslimOseni** [aurelhubert/ahbottomnavigation#388]
While trying to combine AHBottomNavigation and a ViewPager, there was a conflict between `android.app.FragmentManager` (for the AHBottomNavigation) and `android.support.v4.app.FragmentManager` (for the ViewPager). I asked a [question](https://stackoverflow.com/q/52546342/5670752) about this already on StackOverflow.

`android.app.*` packages are deprecated. I think a movement towards `android.support.v4.app.*` should be considered.

**Comment by Eipeks** [comment]
Open a PR with a fix.
