### ISSUE TITLE
Issue with indicator

### ISSUE THREAD

**Issue by juanpaternina** [aurelhubert/ahbottomnavigation#4]
Hi,

First at all excelente work, i'm testing in my project but i having one issue but i'm not 
found any report about that.

All the tabs are selecting when i choose one at one.

See the image below.

Regards.

![screenshot_20160318-135759](https://cloud.githubusercontent.com/assets/386568/13889912/f876ff32-ed16-11e5-8a0b-19e65cb89fbb.png)

**Comment by aurelhubert** [comment]
Hi @juanpaternina, thanks for the feedback. Do you have more details about the problem? Your android version, your implementation, etc.?

**Comment by juanpaternina** [comment]
Hi @aurelhubert, thanks for your response.

I'm working with android N Preview 1 (Nexus 6) and android 4.4.4 Samsung Galaxy Nexus and Both have the problem. 

My implementation is in the next link.

[http://pastebin.com/L3g2VfQF](url)

I try with the example code too and y have the same problem.

**Comment by juanpaternina** [comment]
Hi again.. i'm using the last versión 0.1.2 and now is working.

Thanks you.
