### ISSUE TITLE
Change icon when  item selected

### ISSUE THREAD

**Issue by zhweeant** [aurelhubert/ahbottomnavigation#40]
Can we change the icon when item selected. thanks

**Comment by aurelhubert** [comment]
@zhweeant For now, no. The library is only here to reproduce what the Bottom Navigation should be (with the Material Design guidelines). You can fork the project if you want to add or modify some behaviors which don't follow the guidelines.

**Comment by EduardoDornel** [comment]
this is possible today ?

**Comment by piotrkst** [comment]
> this is possible today ?


Yes, use selector as a item's drawable resource:

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/ic_menu_xyz_selected" android:state_selected="true"/>
    <item android:drawable="@drawable/ic_menu_xyz_unselected" android:state_selected="false"/>
</selector>
```
