### ISSUE TITLE
AHBottomNavigation not Scorlling if added inside any child layout 

### ISSUE THREAD

**Issue by Kiran89kumar** [aurelhubert/ahbottomnavigation#43]
AHBottomNavigation is not showing the scorll behaviour, after adding inside any kind of layout.

As its Parent layout should be CoordinatorLayout, so tried by adding inside CoordinatorLayout, still same issue.

**Comment by aurelhubert** [comment]
@Kiran89kumar It's not a bug. You have to put your view as a child of the CoordinatorLayout if you want the animation.
