### ISSUE TITLE
Migrate artifacts from jcenter

### ISSUE THREAD

**Issue by TheFaithOne** [aurelhubert/ahbottomnavigation#430]
Jfrog is going to deprecate and disable jcenter services - artifact migration will be needed

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by ArneKoeckeritz** [comment]
Here is a good guide for a migration to Sonatype.
https://www.sonatype.com/nexus/repository-pro

Guide
https://central.sonatype.org/pages/ossrh-guide.html

**Comment by mochadwi** [comment]
meanwhile for app developers: https://jeroenmols.com/blog/2021/02/04/migratingjcenter/#:~:text=restrict%20the%20usage%20of%20jcenter

<img width="663" alt="Screen Shot 2021-05-19 at 3 53 51 PM" src="https://user-images.githubusercontent.com/7057959/118784677-6aca4200-b8ba-11eb-8265-d75bea05be44.png">

**Comment by TheFaithOne** [comment]
Jcenter will stay as read only repository indefinitely, so I'll be closing this issue.
Quote from the article above:
UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

**Comment by NicolasEymael** [comment]
it looks like jcenter is 100% dead now
do you plan to migrate the artifacts to mven?
