### ISSUE TITLE
How to always display text below item?

### ISSUE THREAD

**Issue by kiaanpillay** [aurelhubert/ahbottomnavigation#44]
Currently I only have text displayed below the selected item. How can I have it always displayed?

**Comment by kiaanpillay** [comment]
Also is there any opposite function to restoreBottomNavigation? I.e. to hide Bottom Navigation

**Comment by aurelhubert** [comment]
@kiaanpillay In the readme:
```java
// Force the titles to be displayed (against Material Design guidelines!)
bottomNavigation.setForceTitlesDisplay(true);
```

And for now, it's not possible to hide deliberately the bottom navigation.

**Comment by kiaanpillay** [comment]
THank you so much
