### ISSUE TITLE
Hide bottom navigation

### ISSUE THREAD

**Issue by kiaanpillay** [aurelhubert/ahbottomnavigation#46]
If possible can you implement a "hideBottomNavigation" function?

**Comment by kiaanpillay** [comment]
Any update on this?

**Comment by aurelhubert** [comment]
Not sur that should be inside the lib. You can simply use the next code:
```java
// Hide bottom navigation
ViewCompat.animate(bottomNavigation)
	.translationY(bottomNavigation.getHeight())
	.setInterpolator(new LinearOutSlowInInterpolator())
	.setDuration(300)
	.start();
```
```java
// Show bottom navigation
ViewCompat.animate(bottomNavigation)
	.translationY(0)
	.setInterpolator(new LinearOutSlowInInterpolator())
	.setDuration(300)
	.start();
```

**Comment by kiaanpillay** [comment]
Isn't that just what restoreBottomNavigation does? So wouldnt having the opposite make sense?

Either way this is perfect! Thank you, worked like a charm

**Comment by aurelhubert** [comment]
@kiaanpillay You can now use:
`hideBottomNavigation(boolean withAnimation)`
`restoreBottomNavigation(boolean withAnimation)`

**Comment by kiaanpillay** [comment]
Thank you so much! That's excellent, as always!
