### ISSUE TITLE
Does the version of Support Library have to be so new?

### ISSUE THREAD

**Issue by boyw165** [aurelhubert/ahbottomnavigation#50]
Does the version of Support Library have to be so new?

**Comment by aurelhubert** [comment]
Not sure, why?

**Comment by boyw165** [comment]
Cause our project doesn't use the latest Support Library for stability. I don't know is it necessary for a model to require that new version of Support Library. Would you please find a minimum and viable version as the dependency?

**Comment by aurelhubert** [comment]
What version do you use?

**Comment by boyw165** [comment]
For support library, it is `23.2.1`.

**Comment by boyw165** [comment]
BTW, how do I map the version on JCenter to this repo?

**Comment by aurelhubert** [comment]
Have you encountered any problems with the support design library `23.3.0`? And you're right, I should add a change log file, it's not done yet.

**Comment by aurelhubert** [comment]
@boyw165 I have added a change log file.

**Comment by boyw165** [comment]
Not sure, I just check out the release note of it and see no necessary to update. By comparing with alternatives, almost of them try to minimize the version of all dependencies.

> @boyw165 I have added a change log file.
Thanks. :D

**Comment by aurelhubert** [comment]
I've updated the dependencies in the latest version (1.1.4).

**Comment by boyw165** [comment]
Thanks. 👍
