### ISSUE TITLE
How to show shadow like the way in design guideline

### ISSUE THREAD

**Issue by boyw165** [aurelhubert/ahbottomnavigation#52]
Sorry for asking the question over and over again. I just want to know how to make the shadow more apparent like the way in design guideline.
I found the shadow position is always a little bit lower to the position of the current view component. But I think we need to customize the shadow so that it's a little bit higher to the position of the current view component.
https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-style

**Comment by aurelhubert** [comment]
The shadow is currently made with the elevation (8dp) (value from the guide lines).

**Comment by boyw165** [comment]
Yep, I know. But somehow the shadow in the guideline for bottom navigation bar is bigger and it does is bigger in the Google Photo App. I believe there's vague or unconsistent parts for the shadow in the guideline. So please check out the screenshot.
![google_photo](https://cloud.githubusercontent.com/assets/6766554/14758669/664302ce-093a-11e6-84bf-d5659aee1425.png)

**Comment by aurelhubert** [comment]
@boyw165 I'm agree with you. However, this library intends to implement the Bottom Navigation describes in the guidelines. It happens sometimes that Google doesn't respect their own guidelines (which is a bit weird I know).

**Comment by boyw165** [comment]
Thanks @aurelhubert .

**Comment by Parth1111** [comment]
A solution: I put my bottom nav bar in a cradview layout and gave an elevation of 8dp to that cardview. Worked!
