### ISSUE TITLE
Ripple effect on item hold

### ISSUE THREAD

**Issue by iraupph** [aurelhubert/ahbottomnavigation#54]
Hello!
I'd like to see if it's possible to add a new feature to show a ripple effect when holding any items of the bar.
I saw this in the Google Photos (see gif below) app and thought it'd be good to have here too.
![ripple](https://cloud.githubusercontent.com/assets/1833584/14751065/84612dd6-089e-11e6-8b21-8738546c05ed.gif)

Thanks!

**Comment by aurelhubert** [comment]
@iraupph Hi! I've just tested the demo project and I think there is already a ripple effect :) Can you confirm me that's what you want? Thanks

**Comment by aurelhubert** [comment]
@iraupph I close this issue for now. If you have more details about you want to add, feel free to re-open the issue and add more details, thanks!

**Comment by iraupph** [comment]
Sorry, I've been kinda out of this project for a while so I could not check this for you. But as soon as I can I'll make sure everything is OK in regards to this issue.

Thanks!

**Comment by iraupph** [comment]
Just getting back to this: it's actually working as expected with the ripple effect on hold.

Thanks for the great work!
