### ISSUE TITLE
Set TypeFace for title of item

### ISSUE THREAD

**Issue by hoangtu23** [aurelhubert/ahbottomnavigation#55]
Can we set TypeFace / custom font type for title of bottom item?

**Comment by hoangtu23** [comment]
@aurelhubert please help

**Comment by aurelhubert** [comment]
Added in 1.1.6

**Comment by Fatimamostafa** [comment]
@aurelhubert Can you please tell me how to implement it?

**Comment by Fatimamostafa** [comment]
@hoangtu23 Did you solve it?

**Comment by omitsis** [comment]
In case someone has the same question: 

**For use TypeFace**

val font = ResourcesCompat.getFont(this, R.font.titillium)
bottomNavigation.setTitleTypeface(font)
