### ISSUE TITLE
can not  set the bottomnavigation background

### ISSUE THREAD

**Issue by panrongfu** [aurelhubert/ahbottomnavigation#56]
like this ：
 // Set background color
    bottomNavigation.setDefaultBackgroundColor(Color.WHITE);

but not useful

**Comment by Shajeel-Afzal** [comment]
Thanks for creating this library. I also want the ability to change the background colour.

**Comment by aurelhubert** [comment]
@panrongfu @Shajeel-Afzal What is the problem with `bottomNavigation.setDefaultBackgroundColor(Color.WHITE);`?

It works perfectly for me. Can you give me more details? (you need to set "colored" to false to avoid using the item background color: `bottomNavigation.setColored(true);`)

**Comment by aurelhubert** [comment]
@panrongfu @Shajeel-Afzal I close this issue for now. If you still encounter this issue, please provide more details about the problem, thanks.

**Comment by nzackoya** [comment]
Still not working, seems you just dropped the project

**Comment by aznj** [comment]
I think what you can do is use your own color like `bottomNavigation.setDefaultBackgroundColor(ContextCompat.getColor(this@MainActivity, R.color.black))`

**Comment by Asmaa-k** [comment]
@aurelhubert 
setting background is working fine in android api level 21 or higher 
in my app the min api 17 and i tried the following solution nothing work
java:
1.bottomNav.setDefaultBackgroundColor(ContextCompat.getColor(mContext,R.color.colorSurface));
2. bottomNav.setBackgroundColor(ContextCompat.getColor(mContext, R.color.colorSurface));
xml:
 android:background="@color/colorSurface"
 android:backgroundTint="@color/colorSurface"
also i tried some solutions from stackoverflow like these
 bottomNav.setColored(true);
 bottomNav.setForceTint(true);
still didn't work
