### ISSUE TITLE
dynamically change the title of item x

### ISSUE THREAD

**Issue by QrShirt** [aurelhubert/ahbottomnavigation#57]
Hello,

I am currently trying to change the title of a specific item. I was expecting AHBottomNavigation to have a getItemAt(position) method, and setTitle(someString)

How can achieve this?

**Comment by aurelhubert** [comment]
Added in 1.1.7

Use getItem(int position) to get an item, and refresh() to force a refresh of your UI (if you change a title for example).

**Comment by juanlabrador** [comment]
Thanks. I needed too.
