### ISSUE TITLE
Update to Android Support Design Library 23.3.0

### ISSUE THREAD

**Issue by MarioKraml** [aurelhubert/ahbottomnavigation#58]
Hi, 

I have seen that your are using the Android Support Design Library 23.2.1, but there is already version 23.3.0 available. Will you update the dependency to avoid conflicts?

**Comment by aurelhubert** [comment]
@MarioKraml Hi, do you have any conflicts in your app? We had a discussion about this subjet #50 
Feel free to give your opinion.

**Comment by MarioKraml** [comment]
@aurelhubert Hey, thanks for your fast response. It turned out that no conflicts have emerged.
