### ISSUE TITLE
The touch ripples are lost after changing from one item to another, when the bottom navigation is colored

### ISSUE THREAD

**Issue by ChristianGarcia** [aurelhubert/ahbottomnavigation#60]
This happens only when the Bottom navigation is colored.

It's reproducible in the demo app provided with the library.

1. Select colored
2. Perform a long press on any of the items, you'll see a touch ripple
3. Change to the second item
4. Try to repeat 2

Expected result: The touch ripples are visible
Actual result: The touch ripples are no longer visible

My assumption is that the circular reveal performed on `backgroundColorView` is covering the items' background, which is weird because `backgroundColorView` is [added as a child view](https://github.com/aurelhubert/ahbottomnavigation/blob/master/ahbottomnavigation/src/main/java/com/aurelhubert/ahbottomnavigation/AHBottomNavigation.java#L188) of `AHBottomNavigation` before the [`LinearLayout` containing the items](https://github.com/aurelhubert/ahbottomnavigation/blob/master/ahbottomnavigation/src/main/java/com/aurelhubert/ahbottomnavigation/AHBottomNavigation.java#L196)

**Comment by aurelhubert** [comment]
@ChristianGarcia Good catch, thank you very much for the pull request, I have written a slightly different fix but it helps me! 👍 It will be included in the next version (1.1.9).
