### ISSUE TITLE
Custom Font Size

### ISSUE THREAD

**Issue by dalwadi2** [aurelhubert/ahbottomnavigation#64]
Hey, can I Set the custom font size in Bottom Navigation Bar ??
Reply ASAP .

Thank you.

**Comment by aurelhubert** [comment]
For now, no. The library was created to follow the guidelines (and so the text sizes) of Material Design. It could be a bit complicated to manage text sizes because there is a small increase of the text size for the selected item (so if we add a method to set the text size, we should think about the difference between selected/unselected item).

**Comment by dalwadi2** [comment]
Yeh,  you can set the size of selected and unselected item when you complete this module let me know ...

if I want that in both time selected and unselected , both item should be in same font and size .can I do that in your library ?
thanks.

**Comment by dalwadi2** [comment]
@aurelhubert Reply ASAP .

**Comment by SherlockOy** [comment]
Actually, Material Design is meant for English letters, but in the cases of other language, like Chinese Or Japanese, the size of text in BottomNavigation seems to be too big. So I believe it necessary to add this function to the library so we can adjust the text to look nice. Hope you consider this.

**Comment by dalwadi2** [comment]
Okay Good luck @SherlockOy

**Comment by aurelhubert** [comment]
@SherlockOy @dalwadi2 Thanks for your feedback, I will think about the best way to manage this problem.

**Comment by SherlockOy** [comment]
@aurelhubert Cool, looking forward to the solution.

**Comment by aurelhubert** [comment]
@SherlockOy @dalwadi2 Implemented in 1.2.0: `setTitleTextSize(float activeSize, float inactiveSize)`

**Comment by dalwadi2** [comment]
Nice @aurelhubert .
Good luck for further enhancements .

**Comment by SherlockOy** [comment]
Soooooo cool! @aurelhubert

**Comment by zahid--ali** [comment]
@aurelhubert  is the text size in sp or dp? as it's creating issue on small size devices

**Comment by aurelhubert** [comment]
The text size is in sp.

**Comment by zahid--ali** [comment]
@aurelhubert are you sure cause it's not working on correctly please confirm.

**Comment by ovidas00** [comment]
The text size isn't work in every devices even if it is sp. @aurelhubert
