### ISSUE TITLE
Using AHBottomNavigationItem() without an icon causes a NPE

### ISSUE THREAD

**Issue by okarm** [aurelhubert/ahbottomnavigation#67]
Hello,  `AHBottomNavigationItem()` default constructor creates an empty item with `null` drawable field, and the navigation bar makes the assumption that all provided navigation items DO have an icon.

Using these empty items within the navigation bar causes a `NullPointerException`. The navigation bar tries to `setTint(int)` on a `null` object reference.

Fix: add a `null` check to that method and other similar methods which make assumptions about nullable fields.

Alternative fix: just make the default constructor private. Question: Why would we need it anyway?

**Comment by shockdesign** [comment]
@okarm I believe looking at the design docs - https://www.google.com/design/spec/components/bottom-navigation.html - that you'd always at least need an icon, and theres no case to have an item without an icon. You're right though, default constructor should be private. It should force the user to use the correct constructor.

**Comment by aurelhubert** [comment]
@shockdesign I will implement the private constructor, thanks for your feedback!

**Comment by aurelhubert** [comment]
Removed the default constructor in the last version (1.2.0)
