### ISSUE TITLE
AHBottomNavigation floats up with the soft keyboard

### ISSUE THREAD

**Issue by shockdesign** [aurelhubert/ahbottomnavigation#68]
I've noticed that when a soft keyboard appears, the AHBottomNavigation will move up to sit on top of it? Is there a way to force it to stay in position?

Note it's setup as per the example documentation, inside a CoordinatorLayout.

And because there is a WebView, the android:windowSoftInputMode is set to "adjustResize". Have noticed when setting to "adjustPan" the BottomNavigation will stay below

**Comment by shockdesign** [comment]
This is now partially fixed with catch to detect when the soft keyboard is displayed.

**Comment by FabianFrank** [comment]
@shockdesign How do you get the partial fix you are talking about?
