### ISSUE TITLE
Notification should can be a little circle without number

### ISSUE THREAD

**Issue by Panl** [aurelhubert/ahbottomnavigation#69]
As the title says, notification badges should can be custom, hope you can add this function.

**Comment by aurelhubert** [comment]
@Panl like an empty circle? So, it could be related to #66

**Comment by aurelhubert** [comment]
Implemented in 1.2.0, for example: `setNotification(" ", 0)`

**Comment by Panl** [comment]
Cool! , Thank you

**Comment by Panl** [comment]
The empty circle was so big that make it ugly, it can be a little dot, that will be better!

**Comment by JadenGu** [comment]
Hi @aurelhubert ,

Yes. It's really a little bit ugly.. Could you please help to fix it? Thanks.

**Comment by whyalwaysmea** [comment]
Hi @aurelhubert ,
if  `setNotification(" ", 0)` , the circle is really big and ugly, and you provide `setNotificationBackground(Drawable drawable)`, but size don't change,only change radius.

**Comment by keerl** [comment]
Is there a solution for this? When I do `setNotification(" ", 0)` the badge is big and ugly, I just want a small red dot. I feel like this should be included as it is specified in Material Design standards https://material.io/design/components/bottom-navigation.html#behavior

**Comment by mancyzbooni** [comment]
@keerl : got any solutions ?
