### ISSUE TITLE
AHBottomNavigationItem constructor parameters

### ISSUE THREAD

**Issue by consp1racy** [aurelhubert/ahbottomnavigation#7]
Current `AHBottomNavigationItem` contructor takes a mixture of resource identifiers and resources. I suggest using two constructors taking only resource identifiers or resources.

Current constructor:

    AHBottomNavigationItem(String, @DrawableRes int, @ColorInt int);

Suggested constructors:

    AHBottomNavigationItem(@TextRes int, @DrawableRes int, @ColorRes int);
    AHBottomNavigationItem(CharSequence, Drawable, @ColorInt int);

**Comment by aurelhubert** [comment]
@consp1racy We will need a context to get the resources data, do you have an idea for the implementation?

**Comment by consp1racy** [comment]
Definitely! `AHBottomNavigationItem` will hold

```
CharSequence text;
@TextRes int textId;
Drawable icon;
@DrawableRes int iconId;
@ColorInt int color;
@ColorRes int colorRes;
```

Setters can look like this:

```
public AHBottomNavigationItem setText(@TextRes int textId) {
    this.text = null;
    this.textId = textId;
    return this;
}

public AHBottomNavigationItem setText(CharSequence text) {
    this.text = text;
    this.textId = 0;
    return this;
}
```

Text will resolve as so:

```
public CharSequence getText(Context context) {
    if (textRes != 0) {
        return context.getResources().getText(textRes);
    }
    return text;
}
```

Similarly for other properties.
