### ISSUE TITLE
Can the notification active margin be made dynamic/smaller?

### ISSUE THREAD

**Issue by shockdesign** [aurelhubert/ahbottomnavigation#70]
As the title, is it possible to be able to set the active margin of the notification to be smaller/dynamically set by the user?

It's something I want to modify as visually it travels too far when an icon is tapped, however think if it can be set it'd allow for some customisation.

**Comment by aurelhubert** [comment]
Implemented in 1.2.0: `setNotificationMarginLeft(int activeMargin, int inactiveMargin)`
