### ISSUE TITLE
Navigating in tab

### ISSUE THREAD

**Issue by Nominalista** [aurelhubert/ahbottomnavigation#72]
How to accomplish something like in Google [example](https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-behavior) where they click on Kodaline album in Music tab, and then new view is showing on top without disappearing bottom bar?

**Comment by aurelhubert** [comment]
@Nominalista Hi, I suggest you to check the next resources:

- Define custom animations: https://developer.android.com/training/material/animations.html
- Animate components between fragments: https://medium.com/@bherbst/fragment-transitions-with-shared-elements-7c7d71d31cbb#.24cvxjnml

You need to share the elements of the first fragment with your second fragment (for exemple, your details fragment).
