### ISSUE TITLE
Allow no animation when more than 3 items

### ISSUE THREAD

**Issue by JonathanAppPartner** [aurelhubert/ahbottomnavigation#73]
Currently there is no way to stop the icon movement animation from happening when there are more than 3 items in the bottom navigation view. It would be great to allow this animation to be disabled even if there are 4 or more items.

**Comment by aurelhubert** [comment]
@JonathanAppPartner Hi, does the animation is a problem? I have follow the guidelines to develop a component as close as possible of what Material Design shows. I think added a new variable will complicate a bit more the code, and will not result in a clean component.

BTW, if you want to have a fixed sized for your tab, you can use `setForceTitlesDisplay`.
