### ISSUE TITLE
Add vector support

### ISSUE THREAD

**Issue by hateum** [aurelhubert/ahbottomnavigation#74]
make this change on item model to add support for vectorDrawable:

`public Drawable getDrawable(Context context) {
        if (drawableRes != 0) {
            VectorDrawableCompat vectorDrawableCompat = VectorDrawableCompat.create(context.getResources(), drawableRes, context.getTheme());
            if (vectorDrawableCompat != null)
                return vectorDrawableCompat;
            return ContextCompat.getDrawable(context, drawableRes);
        }
        return drawable;
    }`

**Comment by aurelhubert** [comment]
@hateum Hi, thanks for the code, do you encounter any problems with the current implementation? Just asking to avoid adding unnecessary code.

**Comment by hateum** [comment]
I need to add icon with vector format. 
This feature is supported with the new version of support library.
The solution is to use vectorDrawableCompat.

**Comment by CCorrado** [comment]
I'm using Vector icons (exported from sketch, imported the svgs with Android Studio 2.1+ which makes .xml files) with the AHBottomNav. Make sure you're importing the vectors and using the vector support library or else you'll have issues.
```
    compile 'com.android.support:support-vector-drawable:23.4.0'
```

**Comment by aurelhubert** [comment]
@hateum I understand what you want to do, but have you any problem to make it working with the current version? I have successfully try to display a vector icon in the bottom bar and everything seems to be okay.

**Comment by hateum** [comment]
@aurelhubert : do you try it with a version below Lollipop ?

**Comment by aurelhubert** [comment]
Yes, I've tried on Android 4.1.1 (API 16) and it works. We had a discussion here #48 

What I've done:

- Create a XML drawable and put it in /res/drawable/bottom_fav.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportHeight="336"
    android:viewportWidth="351">

    <path
        android:fillColor="#007BFF"
        android:pathData="M276.2,336 C274.2,336,272.2,335.5,270.4,334.6 L175.5,284.7    L80.6,334.6
C76.4,336.8,71.3,336.4,67.4,333.6 C63.6,330.8,61.6,326.1,62.4,321.4 L80.5,215.7
L3.8,140.8 C0.4,137.5,-0.8,132.5,0.6,128 C2.1,123.5,6,120.2,10.7,119.5
L116.8,104.1 L164.3,7.9 C166.4,3.6,170.8,0.9,175.5,0.9
C180.3,0.9,184.6,3.6,186.7,7.9 L234.2,104.1 L340.3,119.5
C345,120.2,348.9,123.5,350.4,128 C351.9,132.5,350.6,137.5,347.2,140.8
L270.4,215.6 L288.5,321.3 C289.3,326,287.4,330.7,283.5,333.5
C281.4,335.1,278.8,336,276.2,336 L276.2,336 L276.2,336 Z"
        android:strokeWidth="1" />
</vector>
```
- Create an item:
```java
AHBottomNavigationItem item1 = new AHBottomNavigationItem(R.string.tab_1, R.drawable.bottom_fav, R.color.color_tab_1);
```

**Comment by emartynov** [comment]
If I'm not wrong then gradle android plugin will generate png files from vector drawable for targets below api 21. That is why it works for author.

However, with latest compat library you can use vector drawables below api 21. So no png generation - faster build, smaller apks. But it is not supported by library now

**Comment by aurelhubert** [comment]
@emartynov Thanks for your feedback, what do you suggest exactly?

**Comment by brittonjg** [comment]
@aurelhubert How are you loading the images? ContextCompat.getDrawable should work even with vectors (that haven't been changed to pngs by AS). I can have a look later, when I have more time to see if I can help out.

I am facing the same issues as @emartynov, the app force closes if devices running anything less that lollipop.

**Comment by aurelhubert** [comment]
The method to get the drawable is:
```java
public Drawable getDrawable(Context context) {
	if (drawableRes != 0) {
		return ContextCompat.getDrawable(context, drawableRes);
	}
	return drawable;
}
```

Can you give me some code to test?

**Comment by brittonjg** [comment]
Okay, that's fine.

After checking the module, I think it's because you aren't using the latest support libraries. 23.4 has Vector support back in and without (potentially) as many of the memory leaks that a previous version had (23.1 I think). 

Chris Banes vector Medium post is quite handy - https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.zca8bm1oi

An example Vector Drawable would be:

<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:autoMirrored="true"
    android:height="24dp"
    android:viewportHeight="24.0"
    android:viewportWidth="24.0"
    android:width="24dp">
  <path
      android:fillColor="#FF000000"
      android:pathData="M4,10v7h3v-7L4,10zM10,10v7h3v-7h-3zM2,22h19v-3L2,19v3zM16,10v7h3v-7h-3zM11.5,1L2,6v2h19L21,6l-9.5,-5z"/>
</vector>

**Comment by brittonjg** [comment]
I was quite off, but I have created a new pull request #107 where we can discuss this further.

**Comment by aurelhubert** [comment]
I will add you PR in the next release (probably 1.3.1)

**Comment by aurelhubert** [comment]
The PR has been added in the version 1.3.1 (with an update of the design library version).
