### ISSUE TITLE
Bottom Navigation does not show/hide on scroll of RV.

### ISSUE THREAD

**Issue by CCorrado** [aurelhubert/ahbottomnavigation#76]
I have the Bottom Nav defined as so in an activity_layout.xml file.

```
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <FrameLayout
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <com.aurelhubert.ahbottomnavigation.AHBottomNavigation
        android:id="@+id/bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom" />

</android.support.design.widget.CoordinatorLayout>
```

I have a fragment that gets swapped into the FrameLayout container defined above with the following contents.
```
<android.support.design.widget.CoordinatorLayout
    style="@style/ActivityViewStyle"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/fragment_feed_appbar_layout"
        android:layout_width="match_parent"
        android:layout_height="@dimen/app_bar_height"
        android:fitsSystemWindows="false"
        android:nestedScrollingEnabled="true">
   ....
    </android.support.design.widget.AppBarLayout>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fragment_feed_fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="16dp"
        android:src="@drawable/ic_add_grey_24dp"
        app:contentScrim="?attr/colorPrimary"
        app:layout_anchor="@id/fragment_feed_appbar_layout"
        app:layout_anchorGravity="bottom|end"/>

    <android.support.v7.widget.RecyclerView
        android:id="@+id/fragment_feed_recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clickable="true"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"/>

</android.support.design.widget.CoordinatorLayout>
```

The bar does not show/hide as expected. I'm using the support fragment manager to manage my transactions. Does it not work when the Recycler View is within another Coordinator Layout in the fragment?

**Comment by Johnsonmaung** [comment]
Me too. Something with our layout structure? Pls help me for proper layout implementation. Thanks

**Comment by kvarela** [comment]
Did you call setBehaviorTranslationEnabled(true)?

**Comment by CCorrado** [comment]
Yes, in the activity where I'm declaring the AHBottomNavigation I am declaring
```
bottomNavigation.setBehaviorTranslationEnabled(true);
```

**Comment by aurelhubert** [comment]
@CCorrado Hi, sorry for the delay, I have tried to put your content inside the demo and everything seems to be okay. When I scroll on the recycler view, the bottom bar disappears. Are you talking about the bottom bar or the AppBarLayout?

**Comment by CCorrado** [comment]
Definitely the bottom bar. If that's the case I'll try it myself today and see if I can resolve.

**Comment by aurelhubert** [comment]
Okay, take a look at the demo project, and let me know if you still have problem, thanks!

**Comment by aurelhubert** [comment]
I will close this issue for now. If you have more details about the problem, feel free to re-open the issue, thank you!

**Comment by joshuaGnol** [comment]
Hi , i have an issue of bottom bar not hiding.
Example :  when the screen able to display 8 row of item , my bottom bar wont hide when scrolling and thus block the view of my last row item.
No problem if I have 9 row of item .

**Comment by CCorrado** [comment]
For reference on this, I was able to get this to work in the end! Essentially the bottomnav bar will not hide if your layout also has a CollapsingToolbarLayout. If you get rid of the collapsing toolbar, the bottom nav will show/hide as expected.

**Comment by jemshit** [comment]
@aurelhubert what about ViewPager, and it has ScrollView inside ? i cant make it work

**Comment by jemshit** [comment]
ok it works with NestedScrollView inside ViewPager, i add `app:layout_behavior="@string/appbar_scrolling_view_behavior"` to ViewPager. It doesn't work with ScrollView . Solves my problem

**Comment by raylee4204** [comment]
@aurelhubert can confirm that the show/hide doesn't work with CollapsingToolbarLayout

**Comment by cavega** [comment]
@aurelhubert Is AHBottomNavigation not supposed to show/hide if we enable the scrollflags for the toolbar? With CoordinatorLayout the bottom bar show/hides just fine during scroll. But the moment I add the following to the Toolbar (to show/hide the Toolbar itself) then the bottom bar stops showing/hiding.

```
app:layout_scrollFlags="scroll|enterAlways"
```

I'm using version 2.0.4 of the library. I can open a new issue if needed be.

**Comment by Pedramrn** [comment]
I have this issue too, looks like other bottom navigation libraries have the same issue.

**Comment by zysidea** [comment]
@aurelhubert Hello, could I ask you some question? I hope you can help me about BottomNavigation. I cant hide the BottomNavigation if BottomNavigation and RecyclerVIew is not in the same Layout. For example BottomNavigation+Fragment (include: ViewPager(include: Frament(include : RecyclerView)).

**Comment by deskid** [comment]
@cavega that seems not the issue of AHBottomNavigation. 
you can check the `android.support.v4.view.NestedScrollingChildHelper.startNestedScroll()`

when scrollFlagss set, only the nearest ViewParent , here the inner CoordinatorLayout, has chance to process nested scroll

```java
public boolean startNestedScroll(@ScrollAxis int axes, @NestedScrollType int type) {
        if (hasNestedScrollingParent(type)) {
            // Already in progress
            return true;
        }
        if (isNestedScrollingEnabled()) {
            ViewParent p = mView.getParent();
            View child = mView;
            while (p != null) {
                if (ViewParentCompat.onStartNestedScroll(p, child, mView, axes, type)) {
                    setNestedScrollingParentForType(type, p);
                    ViewParentCompat.onNestedScrollAccepted(p, child, mView, axes, type);
                    return true;
                }
                if (p instanceof View) {
                    child = (View) p;
                }
                p = p.getParent();
            }
        }
        return false;
    }
```

**Comment by Crasheng** [comment]
Hello guys, anyone got to solve the issue, i still facing it?
I am thinking to use bottom margin for the NestedScrollView but how much margin i should set?

**Comment by kvI87** [comment]
Does it work with expandableListView ?
