### ISSUE TITLE
Icon is scaled, even when giving the bar a fixed height

### ISSUE THREAD

**Issue by avivbenshabat** [aurelhubert/ahbottomnavigation#78]
and when i'm giving it a fixed height, the gravity is to TOP

<img width="567" alt="screen shot 2016-05-19 at 12 01 43 pm" src="https://cloud.githubusercontent.com/assets/12007377/15388220/88ad38d2-1db9-11e6-8619-0e7bb66e7bbd.png">

**Comment by aurelhubert** [comment]
@avivbenshabat Hi, if you want to change the bottom bar height, please fork the project. This component  follows the guidelines of the Bottom Bar here: https://www.google.com/design/spec/components/bottom-navigation.html (the minimum number of items is 3, the maximum is 5).
