### ISSUE TITLE
Ripple does not work on Items with Black Backgroud color

### ISSUE THREAD

**Issue by dhagz** [aurelhubert/ahbottomnavigation#8]
The bottom navigation item's onClick ripple effect does not work if set with black background color.

```
int colorBlack = Color.parseColor("#000000");
AHBottomNavigationItem item1 = new AHBottomNavigationItem(getString(R.string.title_1), R.mipmap.ic_my_details, colorBlack);
AHBottomNavigationItem item2 = new AHBottomNavigationItem(getString(R.string.title_2), R.mipmap.ic_profile_club, colorBlack);
AHBottomNavigationItem item3 = new AHBottomNavigationItem(getString(R.string.title_3), R.mipmap.ic_complete_profile, colorBlack);
```

**Comment by aurelhubert** [comment]
@dhagz It's true but I think it's more a design problem in you app. You can use the dark ripple effect (which is white with a low alpha value) and it should be okay:
```xml
<item name="colorControlHighlight">@color/ripple_material_dark</item>
```

**Comment by tejalshah84** [comment]
Hi there - Awesome library thank you.  I want to turn off the ripple effect and I want to have the selected tab's background to change to a chosen color. Currently I can't even set the background color of the bottom nav bar...it defaults to some random hue of grey/purple. I even set colored to true. How can I achieve this?

**Comment by Rifat-Rashid** [comment]
@tejalshah84

In android studio, import the Ahbottomnavigation library as a module. This allows us to make modifications to the library while using the library from the gradle import does not. Once you have imported the module, go to the layout directory and you should see the following XML files:

- bottom_navigation_item.xml
- bottom_navigation_item.xml (v21)

 In both of the layouts, set the background of the framelayout to transparent (#00000000)               [8 zeros]

Hope this helps!
-Rifat
