### ISSUE TITLE
floating action button hide behind AHBottomNavigation when use restoreBottomNavigation and setBehaviorTranslationEnabled enabled

### ISSUE THREAD

**Issue by saber-solooki** [aurelhubert/ahbottomnavigation#80]
Hi, I have fba and bottom navigation in CoordinatorLayout. it work perfectly : 

`com.aurelhubert.ahbottomnavigation.AHBottomNavigation
            android:id="@+id/bottom_navigation"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom"
            android:elevation="20dp"
            />`

`<android.support.design.widget.FloatingActionButton
            android:id="@+id/fab"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="right|bottom"
            android:layout_marginBottom="70dp"
            android:layout_marginRight="@dimen/view_margin_from_parent"
            android:src="@drawable/ic_category"
            android:background="@color/colorAccent"
            />`

assume I click fba and use hideBottomNavigation to hide bottom navigation. also I use setBehaviorTranslationEnabled(false) to unregister bottom navigation to listen to scrolling for coming up.
everything is ok and I want to back every thing to first manner. I use restoreBottomNavigation and setBehaviorTranslationEnabled(true). but when I scroll down , fba hide behind bottom navigation.

**Comment by saber-solooki** [comment]
I check my code again and notice that restoreBottomNavigation doesn't work and bottom navigation doesn't back.

**Comment by saber-solooki** [comment]
I test some code. I use restoreBottomNavigation(false) and refresh() and setBehaviorTranslationEnabled(true) methods and it works. actually I add refresh() method. but when use restoreBottomNavigation(true) fba hide behind bottom navigation again.

**Comment by aurelhubert** [comment]
@saber-solooki Hi, thanks for the feedback, I think you've found a bug 👍 I will fix it in the next release.

**Comment by aurelhubert** [comment]
Fixed in version 1.2.3

**Comment by saber-solooki** [comment]
thanks for your cool library and thanks for your response
