### ISSUE TITLE
Elevation doesn't look right

### ISSUE THREAD

**Issue by kvarela** [aurelhubert/ahbottomnavigation#82]
Thanks for the awesome lib!

I'm trying to meet my designer's requirements for the elevation on the Bottom Bar, but when I call setUseElevation(), it just looks blurry. Here's a screen shot:
![device-2016-05-23-160606](https://cloud.githubusercontent.com/assets/2534096/15487518/c43ae5d8-2102-11e6-978d-7d9f2dcc9882.png)

Here's what we'd like it to look like:
<img width="453" alt="screen shot 2016-05-23 at 16 25 14" src="https://cloud.githubusercontent.com/assets/2534096/15487538/ff046bda-2102-11e6-9852-ab4d3c44e3a8.png">

Since setUseElevation() isn't doing the job, I tried using a custom gradient drawable and placing it directly above the BottomBar, but I'm having trouble getting it to animate down and up with the BottomBar.

Here's what my main Activity layout looks like:
<img width="863" alt="screen shot 2016-05-23 at 16 36 03" src="https://cloud.githubusercontent.com/assets/2534096/15487736/7f9e878e-2104-11e6-923e-636290c48ad0.png">

Is there any way I can get my gradient drawable to move with the BottomBar as it animates?

**Comment by felipeleusin** [comment]
You can probably use a behavior like https://www.bignerdranch.com/blog/customizing-coordinatorlayouts-behavior/

But I would think it may be easier to just fix the elevation

**Comment by kvarela** [comment]
Yeah, I ended up creating my own CoordinatorLayout.Behavior and controlling
it in much the same way as the BottomNavigation, but it wasn't pleasant. :)

**Comment by aurelhubert** [comment]
@kvarela I think managing the drawable with a CoordinatorLayout is the only way if you want to add a custom shadow.

And if you need, I can add a custom method `setUseElevation(boolean useElevation, float elevation)` which could improve the elevation for your project (but maybe not like you wish).

**Comment by aurelhubert** [comment]
The method has been added in version 1.2.3.

**Comment by kvarela** [comment]
Awesome, thanks Aurelian!

**Comment by estavex** [comment]
@aurelhubert that method doesn't work (anymore?). i've set it and i don't have any shadow above my navigation bar
