### ISSUE TITLE
Selection without changing selected tab

### ISSUE THREAD

**Issue by mgursch** [aurelhubert/ahbottomnavigation#84]
Hi

i have the following feature request:

My bottom bar includes 5 items. If i click 4 of them, it should work as indeed. With animation, coloring etc.

If i click one specific it should only call the callback but without changing the selected item, without animation etc.

Can I achive this with the current library implementation? 
I tried to set immediatelly after clicking the last position, but you can se a little animation. this is not very nice.

So it would be great if this feature can be implemented

Thanks a lot for this library.

**Comment by mgursch** [comment]
No comment on this ?

**Comment by aurelhubert** [comment]
Sorry, I will try to found the time to check the issues soon. I think there is a pull request & a discussion about your point here: #75 I let you check. If it's what you want, it would have some impacts on the listener interface.

**Comment by aurelhubert** [comment]
Added in 1.3.0.

**Comment by zoopolitic** [comment]
Just in time)
