### ISSUE TITLE
No way to set coloredTitleColorActive or coloredTitleColorInactive

### ISSUE THREAD

**Issue by yedidyak** [aurelhubert/ahbottomnavigation#89]
I want to use the (awesome) circular reveal feature, so I understand that I need to set the colors for the background via the items. But I also want to set my own colors for selected and inactive tab text and icons. From the code it seems that these are hardcoded. 

Am I missing something?

**Comment by aurelhubert** [comment]
Actually no, the library follows the Material Design guidelines (https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-behavior), that's why you can't. But you can fork the library and add this functionality if you want!

**Comment by yedidyak** [comment]
Thanks for the reply, but there are some examples in the Google material design guide that have colored icons, with a color for the selected icon + text. Especially if the background is a light color.

**Comment by aurelhubert** [comment]
Can you share me one or more links? :)

**Comment by yedidyak** [comment]
In the link you gave with the material spec, some tab icons are light gray, some are dark gray, and some have the selected tab icon and text in green. The spec itself says:

> Tint the active icon with the app’s primary color. Use black or white if the bottom navigation bar is already colored. 

There's currently no way to do that when using the colored option.

**Comment by aurelhubert** [comment]
Added in 1.3.1
```java
setColoredModeColors(@ColorInt int colorActive, @ColorInt int colorInactive)
```
