### ISSUE TITLE
title only shown on active element on navigation bar with 4 icons

### ISSUE THREAD

**Issue by couchcrew-thomas** [aurelhubert/ahbottomnavigation#9]
As described in the title:

My navigation bar contains 4 items but the title is only shown for the active item.
How can I enable that all titles are shown regardless of selected state?

**Comment by aurelhubert** [comment]
@couchcrew-thomas It's the behavior described in the Material Design guidelines: https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-specs

But you can fork the project and change the code in createItems() line 153 to allow the view to display the titles when the view contains 4 items.

**Comment by couchcrew-thomas** [comment]
Coulnd't you still make this configurable via XML / code?

The problem is that the alpha of the inactive text is set in line #310.
If one wants invisible text you could just set the colorInactiveSmall to #0000 by default.

**Comment by aurelhubert** [comment]
@couchcrew-thomas I could add a parameter like "forceTitleDisplay" but you need to have very short title. Sounds good for you?

**Comment by couchcrew-thomas** [comment]
Thanks, that would be great.

**Comment by aurelhubert** [comment]
@couchcrew-thomas So, you only need a parameter to force to display the title of all BottomNavigationItem, that's it? You juste have to change the next parts:

* Add a boolean: forceTitlesDisplay = true
* line 155: if (items.size() == MIN_ITEMS || forceTitlesDisplay) {
* line 180: manage the size for more than 3 items (the current guidelines don't work with more).

I'm not sure it's a good think to add this behavior in the lib, what do you think?

**Comment by couchcrew-thomas** [comment]
The sizes and paddings can be overridden in the xml. The only line where a style is set on the title that cannot be modified using xml is line #310 where the alpha value is set. Another aproach to the issue could be to make all styles settable via XML. For example the title color of a small inactive item could be #0000 (ARGB) by default. Then you'd just have to animate the color as you are already doing and can leave the view's alpha.

If you want to be as close to the specification as possible it would make sense to not include it into the library. I'd fork it then because our UX guys and me agree that users won't understand icons without text.

However you decide: Great work on the library! I did not expect to find anything so fast after the guidelines were changed.

**Comment by aurelhubert** [comment]
@couchcrew-thomas I have added a method called setForceTitlesDisplay(boolean force) in the 0.1.5, it works, but if you have any feedback, feel free to contact me.

**Comment by couchcrew-thomas** [comment]
It now displays the title on more than 3 elements but distributes the items evently across the full width of the display. This looks wrong on the tablet as the icons are too far from each other.

**Comment by aurelhubert** [comment]
@couchcrew-thomas Alright, so you can describe exactly the behavior that you expect (to avoid many iterations)? I've noticed that the title for the selected item is not always correctly displayed because the font size is a bit increased.

**Comment by couchcrew-thomas** [comment]
I would expect that the method only forces titles to be drawn.
The rest of the layout should behave the same regardless of the forced titles.

For example:
A 5 item default navigation does not span across the whole screen on a tablet.
A 5 item navigation with forced titles does span across the while screen.
This should not happen, the item sizes should remain the same.

Regarding the title display based on their font size:
IMO the best solution would be if the TextView sizes based on it's content and overlaps neighbouring views it its too large. This would prevent clipping and the designer can adjust the wording so it does not interfere with other titles. I'll attach an image for better clarification. However, based on how the TextView measures its size this may not be possible.

![Imgur](http://i.imgur.com/Hs5PlKo.png)

**Comment by aurelhubert** [comment]
@couchcrew-thomas It should be okay in the last version (0.1.6). I've updated the item size, the padding (left & right) and the text size.

**Comment by aurelhubert** [comment]
@couchcrew-thomas I close the issue, if it's not okay for you I'll reopen.

**Comment by couchcrew-thomas** [comment]
Thanks, everything works well
