### ISSUE TITLE
Size of notification bubble is not consistent

### ISSUE THREAD

**Issue by youtoou2** [aurelhubert/ahbottomnavigation#90]
the bubble size of notification sometimes shown in a very small size that the notification title is unreadable, and there's no method to set custom size of notification textview.

**Comment by aurelhubert** [comment]
@youtoou2 Can you give me more details about this problem? Screenshots, phone details, data used? Thanks.

**Comment by aurelhubert** [comment]
I will close this issue for now. If you have more details, feel free to re-open this issue, thank you.
