### ISSUE TITLE
How to add a fade transition between the fragments?

### ISSUE THREAD

**Issue by lhscanedo** [aurelhubert/ahbottomnavigation#92]
I want to add a cross-fade animation between the fragments, like the example in Material Design (https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-behavior)

> Transition between active and inactive views using a cross-fade animation.

I had tried to change this:

`viewPager.setCurrentItem(position, false);`

for

`viewPager.setCurrentItem(position);`

And I had added this in my MainActivity:

```
viewPager.setPageTransformer(false, new FadePageTransformer());

...

public class FadePageTransformer implements ViewPager.PageTransformer {
    public void transformPage(View view, float position) {
        view.setTranslationX(view.getWidth() * -position);

        if(position <= -1.0F || position >= 1.0F) {
            view.setAlpha(0.0F);
        } else if( position == 0.0F ) {
            view.setAlpha(1.0F);
        } else {
            // position is between -1.0F & 0.0F OR 0.0F & 1.0F
            view.setAlpha(1.0F - Math.abs(position));
        }
    }
}
```
It actually works, but if I want to go from the first fragment to the last one, it shows all the fragments between them, like a scroll view.

It has a method in the Fragment class (DemoFragment) that I think I can use for a fade-in fade-out transition, but I have no idea of how to implement it, this is the method:

```
/**
 * Called when a fragment will be displayed
 */
public void willBeDisplayed() {
    // Do what you want here, for example animate the content
}
```

Sorry, I am new in android, I still learning, and I hope you can help me, thanks!

**Comment by aurelhubert** [comment]
@lhscanedo I have updated the demo project with animations for the second & third tabs. The simplest way is too put some code in `willBeDisplayed()` & `willBeHidden()` methods, but it's not the only way to animate views ;)
I let you check the code: https://github.com/aurelhubert/ahbottomnavigation/blob/master/demo/src/main/java/com/aurelhubert/ahbottomnavigation/demo/DemoFragment.java

**Comment by lhscanedo** [comment]
@aurelhubert Hi, I saw your code and I installed it in my phones and emulators, but the demo project still not showing animations, is that showing animations for you when you run the demo project?

**Comment by aurelhubert** [comment]
Yes, you can see the animations when you display the tabs 2 to 5. The animations played are fade_in and fade_out XML resources (be sure to pull the last version of the code).

**Comment by lhscanedo** [comment]
I downloaded again the demo project and now is working, thank you so much! ;)

**Comment by jakubjerabek** [comment]
Hi guys, I have tried demo app but I have to say, that fade out animation is not showing at all. The code in willBeHidden() method is executed but the fragment disappear very quickly.
It doesn't matter when you have same background color in all fragments but if you change background to be different from background in AHBottomNavigationViewPager, you will see it.

For example, set background of fragment_demo_list.xml to green and set background of AHBottomNavigationViewPager in activity_home.xml to red, you will see red color over whole display when moving from Menu 2 to Menu 3.

Is there any idea how to solve this issue? Thank you in advance.
