### ISSUE TITLE
how to be compatible with  translucent Navigation Bar

### ISSUE THREAD

**Issue by seasonyuu** [aurelhubert/ahbottomnavigation#93]
I hadn't seen any screenshot about translucent Navigation Bar in README .So how to use it with translucent Navigation Bar?

`android:fitSystemWindow = true` will make the height uncorret.

**Comment by aurelhubert** [comment]
@seasonyuu yes, it's actually in the TODO list in the Readme (https://github.com/aurelhubert/ahbottomnavigation/blob/master/README.md).
Feel free to implement it and ask a PR if you want!
