### ISSUE TITLE
Support complex drawables

### ISSUE THREAD

**Issue by emartynov** [aurelhubert/ahbottomnavigation#97]
I'm not sure if it is against Google guidelines. But my designer asked to show different image if item is selected.

I've implemented it as usual:
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:drawable="@drawable/bottom_navigation_feed_selected" android:state_selected="true"/>
  <item android:drawable="@drawable/bottom_navigation_feed" />
</selector>
```

But this doesn't work

**Comment by aurelhubert** [comment]
Fixed in 1.3.0.

**Comment by valeriachub** [comment]
Hello! With 1.3.0. selectors work like a charm.. BUT with 1.3.3.(the last version) here is an error `E/VectorDrawableCompat: parser error org.xmlpull.v1.XmlPullParserException: Binary XML file line #2<vector> tag requires viewportWidth > 0`

**Comment by valeriachub** [comment]
I Have found the problem. This is class `AHBottomNavigationItem`
So if i change this method like that, the code works brilliant

`    public Drawable getDrawable(Context context) {
//        if (drawableRes != 0) {
//            try {
//                return VectorDrawableCompat.create(context.getResources(), drawableRes, null);
//            } catch (Resources.NotFoundException e) {
//                return ContextCompat.getDrawable(context, drawableRes);
//            }
//        }
//        return drawable;

        if (drawableRes != 0) {
            return ContextCompat.getDrawable(context, drawableRes);
        }
        return drawable;
    }`

Could you please explain the behavior of the method?
