### ISSUE TITLE
How to change icon size for  active and inactive tabs

### ISSUE THREAD

**Issue by vrjgamer** [aurelhubert/ahbottomnavigation#98]
I was wondering is any way to increase the icon size of tabs, 

![screenshot_2016-06-03-20-16-25](https://cloud.githubusercontent.com/assets/10618953/15782820/4fe64cde-29c9-11e6-86e9-529c9140c649.png)

As u can see they are too small.
they are of size 128 x 128.

**Comment by aurelhubert** [comment]
Can you give me more details? You can check the demo project, the drawable folders contains the correct sizes for the icons.

**Comment by vrjgamer** [comment]
ya i checked the sizes and and resized my icons.
That increased the icon size but not much its still small.
i think i need to crop just the main part of the icon. may that will fix my issue.
